{{- if .Values.slamd.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slamd-client
  labels:
    {{- include "common-services.labels" . | nindent 4 }}
spec:
{{- if not .Values.slamd.client.autoscaling.enabled }}
  replicas: {{ .Values.slamd.client.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: slamd-client
  template:
    metadata:
      labels:
        app: slamd-client
    spec:
      {{- with .Values.slamd.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.slamd.client.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-slamd-server
          image: busybox
          command:  ["sh", "-c", "until nc -z slamd 80 > /dev/null; do echo Waiting for slamd on port 80.; sleep 2; done;"]
      containers:
        - name: slamd-client
          image: "{{ .Values.slamd.client.image.repository }}:{{ .Values.slamd.client.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.slamd.client.image.pullPolicy }}
          env:
            - name: SLAMD_ADDRESS
              value: slamd-server
          resources:
          {{- toYaml .Values.slamd.client.resources | nindent 12 }}
      {{- with .Values.slamd.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slamd.client.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slamd.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
