{{- if and .Values.velero.enabled .Values.backupManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-manager-sa
  labels:
    {{- include "common-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup-manager

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-manager-clusterrole
  labels:
    {{- include "common-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup-manager
rules:
  - apiGroups:
      - velero.io
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-manager-binding
  labels:
    {{- include "common-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backup-manager-clusterrole
subjects:
  - kind: ServiceAccount
    name: backup-manager-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
