{
 "title": "Controller - Database",
 "description": "All the data that is presented here is captured by the PromEx Ecto plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/ecto.ex)",
 "tags": [
  "identity-analytics",
  "radiantone",
  "controller"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(bw_controller_prom_ex_prom_ex_status_info, environment)"
    }
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": {
     "query": "label_values(bw_controller_prom_ex_prom_ex_status_info{environment=\"$environment\"}, instance)"
    }
   },
   {
    "name": "repo",
    "label": "Ecto Repo",
    "query": {
     "query": "label_values(bw_controller_prom_ex_ecto_repo_init_status_info, repo)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Idle Time (Average)",
   "type": "stat",
   "description": "The time the connection spent waiting before being checked out for the query.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_ecto_repo_query_idle_time_milliseconds_sum{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"} / bw_controller_prom_ex_ecto_repo_query_idle_time_milliseconds_count{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Connection Queue Time (Average)",
   "type": "stat",
   "description": "The time spent waiting to check out a database connection.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_ecto_repo_query_queue_time_milliseconds_sum{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"} / bw_controller_prom_ex_ecto_repo_query_queue_time_milliseconds_count{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Connection Decode Time (Average)",
   "type": "stat",
   "description": "The time spent decoding the data received from the database.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_ecto_repo_query_decode_time_milliseconds_sum{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"} / bw_controller_prom_ex_ecto_repo_query_decode_time_milliseconds_count{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Connection Execution Time (Average)",
   "type": "stat",
   "description": "The time spent executing the query. This value is the average time across all query types (SELECT, DELETE, etc).",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bw_controller_prom_ex_ecto_repo_query_execution_time_milliseconds_sum{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"}) / sum(bw_controller_prom_ex_ecto_repo_query_execution_time_milliseconds_count{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"})"
    }
   ]
  },
  {
   "title": "Ecto Repo",
   "type": "stat",
   "description": "The name of the Ecto Repo module",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_ecto_repo_init_status_info{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Database Host",
   "type": "stat",
   "description": "The host of the database that the Repo is connected to.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_ecto_repo_init_status_info{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Database Name",
   "type": "stat",
   "description": "The name of the database that the Repo is connected to.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_ecto_repo_init_status_info{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "stat",
   "description": "The pool size that the repo was initialized with.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_ecto_repo_init_pool_size{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Timeout Duration",
   "type": "stat",
   "description": "The timeout duration that the Repo was initialized with.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_ecto_repo_init_timeout_duration{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Query Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Total Execution Time",
     "type": "timeseries",
     "description": "The average total time to execute and decode a database query.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_ecto_repo_query_total_time_milliseconds_sum{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}[$interval])) by(command) / sum(irate(bw_controller_prom_ex_ecto_repo_query_total_time_milliseconds_count{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}[$interval])) by(command)",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "Total Execution Time",
     "type": "heatmap",
     "description": "A heatmap showing the total time spread across all Repo query executions (regardless of query type).",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_ecto_repo_query_execution_time_milliseconds_bucket{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Average Query Execution Time",
     "type": "timeseries",
     "description": "The average query execution time per Ecto command.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_ecto_repo_query_execution_time_milliseconds_sum{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}[$interval])) by(command) / sum(irate(bw_controller_prom_ex_ecto_repo_query_execution_time_milliseconds_count{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}[$interval])) by(command)",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "Query Execution Time",
     "type": "heatmap",
     "description": "A heatmap showing the request time spread across all Repo query executions (regardless of query type).",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_ecto_repo_query_execution_time_milliseconds_bucket{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Operations Per Source",
     "type": "timeseries",
     "description": "The number of operations taking place on each data source.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(increase(bw_controller_prom_ex_ecto_repo_query_execution_time_milliseconds_count{instance=\"$instance\", environment=\"$environment\", repo=\"$repo\"}[$interval])) by(source)",
       "legendFormat": "{{ source }}"
      }
     ]
    },
    {
     "title": "Results Returned",
     "type": "heatmap",
     "description": "A heatmap showing the number of results returned from the database (summed up across all operations and sources).",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_ecto_repo_query_results_returned_bucket{environment=\"$environment\", instance=\"$instance\", repo=\"$repo\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}