{
 "title": "Controller - Virtual Machine",
 "tags": [
  "identity-analytics",
  "radiantone",
  "controller"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(bw_controller_prom_ex_prom_ex_status_info,  radiantlogic_io_environment)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "5m, 15m, 30m, 1h" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bw_controller_prom_ex_prom_ex_status_info{radiantlogic_io_environment=\"$environment\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_uptime_milliseconds_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "OTP Compiler Options",
   "type": "table",
   "description": "Shows the various options that OTP was compiled with.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"bw_controller_prom_ex_beam_system_thread_support_info|bw_controller_prom_ex_beam_system_jit_support_info|bw_controller_prom_ex_beam_system_smp_support_info|bw_controller_prom_ex_beam_system_time_correction_support_info\", radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "OTP Major Version",
   "type": "stat",
   "description": "The OTP major version running the application.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_system_version_info{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "stat",
   "description": "The number of running BEAM processes currently running.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_process_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Information",
   "type": "table",
   "description": "Shows information regarding the schedulers configured for the BEAM instance.",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{__name__=~\"bw_controller_prom_ex_beam_system_dirty_cpu_schedulers_info|bw_controller_prom_ex_beam_system_dirty_cpu_schedulers_online_info|bw_controller_prom_ex_beam_system_dirty_io_schedulers_info|bw_controller_prom_ex_beam_system_schedulers_info|bw_controller_prom_ex_beam_system_schedulers_online_info|bw_controller_prom_ex_beam_system_word_size_bytes_info|bw_controller_prom_ex_beam_system_logical_processors_info|bw_controller_prom_ex_beam_system_logical_processors_available_info|bw_controller_prom_ex_beam_system_logical_processors_online_info\", radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Port Count",
   "type": "stat",
   "description": "The number of currently active ports.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_port_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "ETS Table Count",
   "type": "stat",
   "description": "The number of currently allocated ETS tables.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_ets_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Limits",
   "type": "table",
   "description": "Shows information regarding the system limits of the BEAM instance.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "{__name__=~\"bw_controller_prom_ex_beam_system_ets_limit_info|bw_controller_prom_ex_beam_system_port_limit_info|bw_controller_prom_ex_beam_system_process_limit_info|bw_controller_prom_ex_beam_system_atom_limit_info\", radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "description": "The amount of memory currently allocated by the BEAM.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_memory_allocated_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Atom Count",
   "type": "stat",
   "description": "The number of atoms currently in the atom table.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_atom_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "description": "Stats on the current memory usage.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_memory_allocated_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "bw_controller_prom_ex_beam_memory_atom_total_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "bw_controller_prom_ex_beam_memory_binary_total_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Binaries"
    },
    {
     "expr": "bw_controller_prom_ex_beam_memory_code_total_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "bw_controller_prom_ex_beam_memory_ets_total_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "ETS"
    },
    {
     "expr": "bw_controller_prom_ex_beam_memory_processes_total_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "bw_controller_prom_ex_beam_memory_persistent_term_total_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Persistent Term"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "The number of garbage collection events that are occurring and the number of bytes reclaimed",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(bw_controller_prom_ex_beam_stats_gc_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Garbage Collections"
    },
    {
     "expr": "irate(bw_controller_prom_ex_beam_stats_gc_reclaimed_bytes{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "Normal Scheduler Status",
   "type": "timeseries",
   "description": "Statistics regarding the normal scheduler.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_active_task_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\", type=\"normal\"}",
     "legendFormat": "Normal Tasks"
    },
    {
     "expr": "0 - bw_controller_prom_ex_beam_stats_run_queue_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\", type=\"normal\"}",
     "legendFormat": "Normal Run Queue"
    }
   ]
  },
  {
   "title": "Dirty Scheduler Status",
   "type": "timeseries",
   "description": "Statistics regarding the dirty schedulers.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_active_task_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\", type=\"dirty\"}",
     "legendFormat": "Dirty Tasks"
    },
    {
     "expr": "0 - bw_controller_prom_ex_beam_stats_run_queue_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\", type=\"dirty\"}",
     "legendFormat": "Dirty Run Queue"
    }
   ]
  },
  {
   "title": "VM Load",
   "type": "timeseries",
   "description": "The number of context switches that have occured along with the number of reductions.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(bw_controller_prom_ex_beam_stats_reduction_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}[$interval]) / 1000000",
     "legendFormat": "Reductions"
    },
    {
     "expr": "irate(bw_controller_prom_ex_beam_stats_context_switch_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Active BEAM Processes",
   "type": "timeseries",
   "description": "The number of running BEAM processes.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_process_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Active Processes"
    }
   ]
  },
  {
   "title": "Atom Table Size",
   "type": "timeseries",
   "description": "The number of atoms currently in the atom table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_atom_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Active ports"
    }
   ]
  },
  {
   "title": "Port IO",
   "type": "timeseries",
   "description": "The number of bytes sent and received through ports.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "0 - irate(bw_controller_prom_ex_beam_stats_port_io_byte_count{radiantlogic_io_environment=\"$environment\", type=\"input\"}[$interval])",
     "legendFormat": "Data Received"
    },
    {
     "expr": "irate(bw_controller_prom_ex_beam_stats_port_io_byte_count{radiantlogic_io_environment=\"$environment\", type=\"output\"}[$interval])",
     "legendFormat": "Data Sent"
    }
   ]
  },
  {
   "title": "ETS Tables",
   "type": "timeseries",
   "description": "The number of active ETS tables.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_ets_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Active ETS Tables"
    }
   ]
  },
  {
   "title": "Active Ports",
   "type": "timeseries",
   "description": "The number of active ports.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_beam_stats_port_count{radiantlogic_io_environment=\"$environment\", instance=\"$instance\"}",
     "legendFormat": "Active Ports"
    }
   ]
  }
 ]
}