{
 "title": "Controller - Queue Manager",
 "description": "All the data that is presented here is captured by the PromEx Oban plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/oban.ex)",
 "tags": [
  "identity-analytics",
  "controller",
  "radiantone"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(bw_controller_prom_ex_prom_ex_status_info, environment)"
    }
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": {
     "query": "label_values(bw_controller_prom_ex_prom_ex_status_info{environment=\"$environment\"}, instance)"
    }
   },
   {
    "name": "oban",
    "label": "Oban Instance",
    "query": {
     "query": "label_values(bw_controller_prom_ex_oban_init_status_info, name)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oban Time Limit Settings",
   "type": "table",
   "description": "The configuration of the selected Oban instance",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"bw_controller_prom_ex_oban_init_shutdown_grace_period_milliseconds|bw_controller_prom_ex_oban_init_poll_interval_milliseconds|bw_controller_prom_ex_oban_init_dispatch_cooldown_milliseconds\", environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}"
    }
   ]
  },
  {
   "title": "Available Jobs in Queue",
   "type": "bargauge",
   "description": "The number of jobs in each queue that are in the available state.",
   "gridPos": { "h": 12, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_oban_queue_length_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\", state=\"available\"}",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Oban Configuration",
   "type": "table",
   "description": "The configuration of the selected Oban instance",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=\"bw_controller_prom_ex_oban_init_status_info\", environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}"
    }
   ]
  },
  {
   "title": "Queue Concurrency Limits",
   "type": "table",
   "description": "The configured concurrency limits for each of the queues under the Oban supervisor.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_oban_init_queue_concurrency_limit{instance=\"$instance\", environment=\"$environment\", name=\"$oban\"}"
    }
   ]
  },
  {
   "title": "Processed Jobs (by $interval interval)",
   "type": "stat",
   "description": "The number of jobs processed across all queues and states.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(bw_controller_prom_ex_oban_job_processing_duration_milliseconds_count{instance=\"$instance\", environment=\"$environment\", name=\"$oban\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Job Errors (by $interval interval)",
   "type": "stat",
   "description": "The number of jobs that resulted in an error across all queues.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(bw_controller_prom_ex_oban_job_exception_duration_milliseconds_count{instance=\"$instance\", environment=\"$environment\", name=\"$oban\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Jobs Enqueued (by $interval interval)",
   "type": "stat",
   "description": "The number of jobs that have been enqueued.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(bw_controller_prom_ex_oban_producer_dispatched_count_count{instance=\"$instance\", environment=\"$environment\", name=\"$oban\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Successful Job Processing Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Job Execution Time",
     "type": "heatmap",
     "description": "A heatmap showing the time it took to process jobs across all queues.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_oban_job_processing_duration_milliseconds_bucket{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Job Queue Time",
     "type": "heatmap",
     "description": "A heatmap showing how long jobs are waiting in queue for processing.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_oban_job_queue_time_milliseconds_bucket{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Average Job Execution Time",
     "type": "timeseries",
     "description": "The average time it took to process jobs per queue. This will include jobs that ended with a successful, snoozed, or discarded state.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_job_processing_duration_milliseconds_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_job_processing_duration_milliseconds_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "({{ state }}) {{ name }} :: {{ worker }}"
      }
     ]
    },
    {
     "title": "Average Job Queue Time",
     "type": "timeseries",
     "description": "The average time a job waited in queue for processing.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_job_queue_time_milliseconds_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_job_queue_time_milliseconds_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "({{ state }}) {{ name }} :: {{ worker }}"
      }
     ]
    },
    {
     "title": "Average Job Attempts",
     "type": "timeseries",
     "description": "The average time it took to process jobs per queue. This will include jobs that ended with a successful, snoozed, or discarded state.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_job_complete_attempts_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_job_complete_attempts_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "({{ state }}) {{ name }} :: {{ worker }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Error Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Job Execution Time",
     "type": "heatmap",
     "description": "A heatmap showing the time it took to process jobs across all queues that resulted in an error.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_oban_job_exception_duration_milliseconds_bucket{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Job Queue Time",
     "type": "heatmap",
     "description": "A heatmap showing how long jobs are waiting in queue for processing that resulted in an error.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_oban_job_exception_queue_time_milliseconds_bucket{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Average Job Execution Time",
     "type": "graph",
     "description": "The average time it took to process jobs per queue that resulted in an error.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ms", "label": "Execution Time" }
     ],
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_job_exception_duration_milliseconds_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_job_exception_duration_milliseconds_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "({{ error }}) {{ name }} :: {{ worker }}"
      }
     ]
    },
    {
     "title": "Average Job Queue Time",
     "type": "graph",
     "description": "The average time a job waited in queue for processing prior to resulting in an error.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "ms", "label": "In Queue Time" }
     ],
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_job_exception_queue_time_milliseconds_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_job_exception_queue_time_milliseconds_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "({{ error }}) {{ name }} :: {{ worker }}"
      }
     ]
    },
    {
     "title": "Average Job Failure Attempts",
     "type": "graph",
     "description": "The average time it took to process jobs per queue that resulted in an error.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "locale", "label": "Job Attempts" }
     ],
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_job_exception_attempts_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_job_exception_attempts_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "({{ state }}) {{ name }} :: {{ worker }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Available Jobs per Queue",
     "type": "timeseries",
     "description": "The number of jobs marked as available in each queue.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bw_controller_prom_ex_oban_queue_length_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\", state=\"available\"}",
       "legendFormat": "{{ queue }}"
      }
     ]
    },
    {
     "title": "Completed Jobs per Queue",
     "type": "timeseries",
     "description": "The number of jobs marked as completed in each queue.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bw_controller_prom_ex_oban_queue_length_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\", state=\"completed\"}",
       "legendFormat": "{{ queue }}"
      }
     ]
    },
    {
     "title": "Executing Jobs per Queue",
     "type": "timeseries",
     "description": "The number of jobs marked as executing in each queue.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bw_controller_prom_ex_oban_queue_length_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\", state=\"executing\"}",
       "legendFormat": "{{ queue }}"
      }
     ]
    },
    {
     "title": "Retryable Jobs per Queue",
     "type": "timeseries",
     "description": "The number of jobs marked as retryable in each queue.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bw_controller_prom_ex_oban_queue_length_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\", state=\"retryable\"}",
       "legendFormat": "{{ queue }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Producer Dispatch Time",
     "type": "heatmap",
     "description": "A heatmap showing how long jobs to be dispatched.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_oban_producer_duration_milliseconds_bucket{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Producer Dispatch Count",
     "type": "heatmap",
     "description": "A heatmap showing the number of jobs that were dispatched.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(irate(bw_controller_prom_ex_oban_producer_dispatched_count_bucket{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Average Dispatch Time",
     "type": "timeseries",
     "description": "The average amount of time it took to dispatch jobs to each queue.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_producer_duration_milliseconds_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_producer_duration_milliseconds_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "{{ queue }}"
      }
     ]
    },
    {
     "title": "Average Dispatch Count",
     "type": "timeseries",
     "description": "The average number of jobs dispatched to each queue.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_producer_dispatched_count_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_producer_dispatched_count_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "{{ queue }}"
      }
     ]
    },
    {
     "title": "Average Exception Duration",
     "type": "timeseries",
     "description": "The average amount of time it took to encounter an encounter an error.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(bw_controller_prom_ex_oban_producer_exception_duration_milliseconds_sum{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval]) / irate(bw_controller_prom_ex_oban_producer_exception_duration_milliseconds_count{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "{{ queue }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit Breaker Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Circuit Trip Events (last 1 hour)",
     "type": "stat",
     "description": "This is the total number of trip events that have been encountered by the selected application and Oban instances.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(bw_controller_prom_ex_oban_circuit_trip_total{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[1h])"
      }
     ]
    },
    {
     "title": "Total Circuit Trip Events",
     "type": "stat",
     "description": "This is the total number of trip events that have been encountered by the selected application and Oban instances.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bw_controller_prom_ex_oban_circuit_trip_total{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}"
      }
     ]
    },
    {
     "title": "Circuit Open Events (last 1 hour)",
     "type": "stat",
     "description": "This is the total number of open events that have been encountered by the selected application and Oban instances.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(bw_controller_prom_ex_oban_circuit_open_total{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[1h])"
      }
     ]
    },
    {
     "title": "Total Circuit Open Events",
     "type": "stat",
     "description": "This is the total number of open events that have been encountered by the selected application and Oban instances.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bw_controller_prom_ex_oban_circuit_open_total{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}"
      }
     ]
    },
    {
     "title": "Circuit Breaker Trip Events",
     "type": "timeseries",
     "description": "The number of circuit breaker trip events that occured along with what component tripped the breaker.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(bw_controller_prom_ex_oban_circuit_trip_total{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "{{ circuit_breaker }}"
      }
     ]
    },
    {
     "title": "Circuit Breaker Open Events",
     "type": "timeseries",
     "description": "The number of circuit breaker open events that occured along with what component tripped the breaker.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(bw_controller_prom_ex_oban_circuit_open_total{environment=\"$environment\", instance=\"$instance\", name=\"$oban\"}[$interval])",
       "legendFormat": "{{ circuit_breaker }}"
      }
     ]
    }
   ]
  }
 ]
}