{
 "title": "Data Ingestion",
 "description": "Data Ingestion",
 "tags": [
  "identity-analytics",
  "data-ingestion",
  "radiantone"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(radiantlogic_io_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{radiantlogic_io_environment=\"$environment\", app=\"batch\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{radiantlogic_io_environment=\"$environment\", app=\"batch\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_availableprocessors{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalphysicalmemorysize{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalswapspacesize{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(5m avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_operatingsystem_systemcpuload{radiantlogic_io_environment=\"$environment\", app=\"batch\"}[5m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\", radiantlogic_io_environment=\"$environment\", app=\"batch\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\", radiantlogic_io_environment=\"$environment\", app=\"batch\"})"
    }
   ]
  },
  {
   "title": "Memory Heap / NonHeap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{radiantlogic_io_environment=\"$environment\", app=\"batch\"} / ignoring(area) group_left java_lang_operatingsystem_totalphysicalmemorysize{radiantlogic_io_environment=\"$environment\", app=\"batch\"} * 100",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{radiantlogic_io_environment=\"$environment\", app=\"batch\"} * 100",
     "legendFormat": "system"
    },
    {
     "expr": "java_lang_operatingsystem_processcpuload{radiantlogic_io_environment=\"$environment\", app=\"batch\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Current threads"
    },
    {
     "expr": "jvm_threads_daemon{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Deadlocked threads"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"PS Eden Space\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Eden Space\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Eden Space\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"PS Old Gen\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Old Gen\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Old Gen\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"PS Survivor Space\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Survivor Space\", environment=\"$environment\", app=\"batch\", batch_id=\"$batch_id\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Survivor Space\", environment=\"$environment\", app=\"batch\", batch_id=\"$batch_id\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Classes loading",
   "type": "timeseries",
   "description": "The number of classes that are currently loaded in the JVM",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Loaded classes"
    },
    {
     "expr": "jvm_classes_unloaded_total{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Uninstall classes"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\", radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{radiantlogic_io_environment=\"$environment\", app=\"batch\"}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{radiantlogic_io_environment=\"$environment\", app=\"batch\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}