{
 "title": "IDA Dashboard",
 "description": "General overview",
 "tags": [
  "monitoring",
  "identity-analytics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(radiantlogic_io_environment)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "cnpg_collector_up{cluster=\"shared-db\", service=\"shared-db-metrics\", radiantlogic_io_environment=\"$environment\"}"
    }
   },
   { "name": "interval", "label": "interval", "query": "5m,15m,30m,1h,6h,12h,1d" },
   {
    "name": "controller_instance",
    "label": "controller_instance",
    "query": {
     "query": "label_values(bw_controller_prom_ex_prom_ex_status_info{radiantlogic_io_environment =\"$environment\"}, instance)"
    }
   },
   {
    "name": "extractor_instance",
    "label": "extractor_instance",
    "query": {
     "query": "label_values(python_info{radiantlogic_io_environment=\"$environment\", app=\"extractor-web\"}, instance)"
    }
   },
   {
    "name": "portal_instance",
    "label": "portal_instance",
    "query": {
     "query": "label_values(up{radiantlogic_io_environment=\"$environment\", app=\"portal\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Governance Portal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Used ($interval)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}[$interval])\n) by (pod)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app=\"portal\", radiantlogic_io_environment=\"$environment\", area=\"heap\"} / jvm_memory_bytes_max{app=\"portal\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ledger DB Pool Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalina_datasource_idle{app=\"portal\", radiantlogic_io_environment=\"$environment\", name=\"\\\"jdbc/BRAINWAVEDB\\\"\"} / catalina_datasource_maxactive{app=\"portal\", radiantlogic_io_environment=\"$environment\", name=\"\\\"jdbc/BRAINWAVEDB\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{app=\"portal\", radiantlogic_io_environment=\"$environment\"} - tomcat_session_expiredsessions_total)",
     "legendFormat": "Current count"
    },
    {
     "expr": "sum(tomcat_session_sessioncounter_total{app=\"portal\", radiantlogic_io_environment=\"$environment\"})",
     "legendFormat": "Total created"
    },
    {
     "expr": "sum(tomcat_session_expiredsessions_total{app=\"portal\", radiantlogic_io_environment=\"$environment\"})",
     "legendFormat": "Total expired"
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{radiantlogic_io_environment=~\"$environment\", app=\"portal\", instance=\"$portal_instance\"}",
     "legendFormat": "Current threads"
    },
    {
     "expr": "jvm_threads_daemon{radiantlogic_io_environment=~\"$environment\", app=\"portal\", instance=\"$portal_instance\"}",
     "legendFormat": "Daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{radiantlogic_io_environment=~\"$environment\", app=\"portal\", instance=\"$portal_instance\"}",
     "legendFormat": "Deadlocked threads"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{app=\"portal\", radiantlogic_io_environment=\"$environment\"})*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"portal\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ($interval)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "description": "Last Java heap measured while data ingestion ran",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app=\"portal\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow DB Pool usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalina_datasource_idle{app=\"portal\", radiantlogic_io_environment=\"$environment\", name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"} / catalina_datasource_maxactive{app=\"portal\", radiantlogic_io_environment=\"$environment\", name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of pod memory",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total heap memory available",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{app=\"portal\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ($interval)",
   "type": "timeseries",
   "description": "CPU usage with throttling percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}[$interval]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"} [$interval])) / sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"}[$interval]))",
     "legendFormat": "CPU Throttle %"
    }
   ]
  },
  {
   "title": "Tomcat Request Processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "catalina_globalrequestprocessor_bytesreceived_total{radiantlogic_io_environment=\"$environment\", instance=~\"$portal_instance\", port=\"8080\"}",
     "legendFormat": "received"
    },
    {
     "expr": "catalina_globalrequestprocessor_bytessent_total{radiantlogic_io_environment=\"$environment\", instance=~\"$portal_instance\", port=\"8080\"}",
     "legendFormat": "sent"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Used ($interval)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}[$interval])\n) by (pod, container)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}\n) by (pod, container)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (cnpg_backends_total{radiantlogic_io_environment=~\"$environment\", service=\"shared-db-metrics\"}) / sum(cnpg_pg_settings_setting{name=\"max_connections\", radiantlogic_io_environment=~\"$environment\", service=\"shared-db-metrics\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "bargauge",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)$\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)$\"}) / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)$\"}",
     "legendFormat": "DATA"
    },
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)-wal\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)-wal\"}) / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)-wal\"}",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "Analytics DB size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (datname) (cnpg_pg_database_size_bytes{radiantlogic_io_environment=\"$environment\", datname=\"analytics_db\", service=\"shared-db-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "description": "Total number of backends that are currently waiting on other queries",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_backends_waiting_total{namespace=\"$namespace\", service=\"shared-db-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_start_time_seconds{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)\", container=\"postgres\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archived",
   "type": "stat",
   "description": "Last WAL archived",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\", service=\"shared-db-metrics\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", service=\"shared-db-metrics\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", service=\"shared-db-metrics\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shared DB size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (datname) (cnpg_pg_database_size_bytes{radiantlogic_io_environment=\"$environment\", datname=\"shared_db\", service=\"shared-db-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "description": "Number of deadlocks detected in Analytics DB over 5 minutes",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_stat_database_deadlocks{namespace=\"$namespace\", datname=\"analytics_db\", service=\"shared-db-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)\", container=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "bargauge",
   "description": "Number of transactions from the frozen XID to the current one",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_database_xid_age{namespace=\"$namespace\", datname=\"analytics_db\", service=\"shared-db-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ($interval)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}[$interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (\n  (\n    max \n    (\n      max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)([a-z-]*)\"} \n      / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)([a-z-]*)\"})\n    )\n  )\n  OR\n  (\n    max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)([a-z-]*)\"}\n    / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)([a-z-]*)\"})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage size",
   "type": "stat",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)$\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)$\"})",
     "legendFormat": "DATA"
    },
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)-wal\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)-wal\"})",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of pod memory",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization ($interval)",
   "type": "timeseries",
   "description": "The disk I/O utilization metrics are bytes written and read.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)\", container=\"postgres\"}[$interval]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum by (interface) (rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)\", container=\"postgres\"}[$interval]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Network ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU used ($interval)",
   "type": "gauge",
   "description": "CPU Utilization",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"}[$interval])\n) by (pod)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (\n  (\n    max \n    (\n      max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-controller-[0-9]*\"} \n      / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-controller-[0-9]*\"})\n    )\n  )\n  OR\n  (\n    max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-controller-[0-9]*\"}\n    / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-controller-[0-9]*\"})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_start_time_seconds{namespace=\"$namespace\", pod=~\"controller-([0-9]*)\", container=\"controller\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "gauge",
   "description": "The number of bytes sent through ports.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(bw_controller_prom_ex_beam_stats_port_io_byte_count{radiantlogic_io_environment=\"$environment\", type=\"input\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "gauge",
   "description": "The number of bytes received through ports. ",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(bw_controller_prom_ex_beam_stats_port_io_byte_count{radiantlogic_io_environment=\"$environment\", instance=~\"$controller_instance\",type=\"output\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Transferred ($interval)",
   "type": "stat",
   "description": "The amount of data transferred by the Controller in the past interval.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bw_controller_prom_ex_phoenix_http_response_size_bytes_sum{radiantlogic_io_environment=\"$environment\", instance=~\"$controller_instance\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\", pod=~\"controller-([0-9]*)\", container=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ($interval)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"}[$interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"}) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "bargauge",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-controller-[0-9]*\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-controller-[0-9]*\"}) / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-controller-[0-9]*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Jobs Processed ($interval)",
   "type": "stat",
   "description": "The number of jobs processed across all queues and states.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(bw_controller_prom_ex_oban_job_processing_duration_milliseconds_count{instance=~\"$controller_instance\", radiantlogic_io_environment=\"$environment\", name=\"Oban\"}[$interval])))",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Jobs Executing",
   "type": "stat",
   "description": "The number of jobs marked as executing in each queue.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_oban_queue_length_count{radiantlogic_io_environment=\"$environment\", instance=~\"$controller_instance\", name=\"Oban\", state=\"executing\"}",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Jobs Retryable",
   "type": "stat",
   "description": "The number of jobs marked as retryable in each queue.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_oban_queue_length_count{radiantlogic_io_environment=\"$environment\", instance=~\"$controller_instance\", name=\"Oban\", state=\"retryable\"}",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Jobs Errors",
   "type": "stat",
   "description": "The number of jobs that resulted in an error across all queues.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bw_controller_prom_ex_oban_job_exception_duration_milliseconds_count{radiantlogic_io_environment=\"$environment\", instance=~\"$controller_instance\", name=\"Oban\"}",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of pod memory",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\", container=\"controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Upload ($interval)",
   "type": "stat",
   "description": "The number of upload jobs in each status.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(state) (increase(bw_controller_prom_ex_oban_queue_length_count{radiantlogic_io_environment=\"$environment\", instance=~\"$controller_instance\", name=\"Oban\", queue=\"uploads\"}[$interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Email ($interval)",
   "type": "stat",
   "description": "The number of email jobs in each status.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(state) (increase(bw_controller_prom_ex_oban_queue_length_count{radiantlogic_io_environment=\"$environment\", instance=~\"$controller_instance\", name=\"Oban\", queue=\"emails\"}[$interval])))",
     "legendFormat": "scheduled"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization ($interval)",
   "type": "timeseries",
   "description": "The disk I/O utilization metrics are bytes written and read.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum by (interface) (rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Network ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"controller-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Data Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "CPU used",
   "type": "gauge",
   "description": "CPU Utilization",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}[$interval])\n) by (pod)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "description": "Last Java heap measured while data ingestion ran",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app=\"batch\", radiantlogic_io_environment=\"$environment\", area=\"heap\"} / jvm_memory_bytes_max{app=\"batch\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_start_time_seconds{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)\", container=\"batch-server\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (\n  (\n    max \n    (\n      max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-batch-server-[0-9]*\"} \n      / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-batch-server-[0-9]*\"})\n    )\n  )\n  OR\n  (\n    max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-batch-server-[0-9]*\"}\n    / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-batch-server-[0-9]*\"})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "bargauge",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-batch-server-([0-9]*)$\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-batch-server-([0-9]*)$\"}) / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-batch-server-([0-9]*)$\"}",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)\", container=\"batch-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ($interval)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}[$interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of pod memory",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "description": "Last Java heap measured while data ingestion ran",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app=\"batch\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total heap memory available",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{app=\"batch\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ($interval)",
   "type": "timeseries",
   "description": "CPU usage with throttling percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}[$interval])) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"} [$interval])) / sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\", container=\"batch-server\"}[$interval])) * 100",
     "legendFormat": "CPU Throttle %"
    }
   ]
  },
  {
   "title": "Network ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"batch-server-([0-9]*)$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Extractor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "CPU Used ($interval)",
   "type": "gauge",
   "description": "CPU Utilization",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"extractor-(.*)\"}[$interval])\n) by (pod)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"extractor-(.*)\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"extractor-(.*)\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"extractor-(.*)$\", container=\"extractor-web\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"extractor-(.*)$\", container=\"extractor-web\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput ($interval)",
   "type": "gauge",
   "description": "Number of requests per seconds",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_duration_seconds_count{radiantlogic_io_environment=\"$environment\", instance=~\"$extractor_instance\", path=~\"/v1.0/extractors/(.*)\", status=\"200\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors ($interval)",
   "type": "gauge",
   "description": "Number of failed (non HTTP 200) responses per second.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_duration_seconds_count{radiantlogic_io_environment=\"$environment\", instance=~\"$extractor_instance\", status!=\"200\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_start_time_seconds{namespace=\"$namespace\", pod=~\"extractor-(.*)\", container=\"extractor-web\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"extractor-(.*)\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"extractor-(.*)\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\", pod=~\"extractor-(.*)\", container=\"extractor-web\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ($interval)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"extractor-(.*)$\", container=\"extractor-web\"}[$interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"extractor-(.*)$\", container=\"extractor-web\"}) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"extractor-(.*)$\", container=\"extractor-web\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"extractor-(.*)$\", container=\"extractor-web\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of pod memory",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"extractor-(.*)$\", container=\"extractor-web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Git Sync Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "CPU Used ($interval)",
   "type": "gauge",
   "description": "CPU Utilization",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}[$interval])\n) by (pod)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_start_time_seconds{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (\n  (\n    max \n    (\n      max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-git-server-[0-9]*\"} \n      / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-git-server-[0-9]*\"})\n    )\n  )\n  OR\n  (\n    max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-git-server-[0-9]*\"}\n    / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-git-server-[0-9]*\"})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "bargauge",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-git-server-[0-9]*\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-git-server-[0-9]*\"}) / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-git-server-[0-9]*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ($interval)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}[$interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of pod memory",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sync",
   "type": "stat",
   "description": "How many git syncs completed",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (git_sync_count_total{radiantlogic_io_environment=\"$environment\", app=\"git-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sync successful",
   "type": "stat",
   "description": "How many git syncs completed sucessfully",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(git_sync_count_total{radiantlogic_io_environment=\"$environment\", app=\"git-server\", status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sync with failures",
   "type": "stat",
   "description": "How many git syncs completed with failures",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (git_sync_count_total{radiantlogic_io_environment=\"$environment\", app=\"git-server\", status=\"error\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Success",
   "type": "stat",
   "description": "How many git syncs completed successfully in the range",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(git_sync_count_total{radiantlogic_io_environment=\"$environment\", app=\"git-server\", status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync with failures",
   "type": "stat",
   "description": "How many git syncs completed with failures in the range",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(git_sync_count_total{radiantlogic_io_environment=\"$environment\", app=\"git-server\", status=\"error\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ($interval)",
   "type": "timeseries",
   "description": "CPU usage with throttling percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}[$interval])) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"} [$interval])) / sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"git-server-([0-9]*)$\", container=\"git-server\"}[$interval])) * 100",
     "legendFormat": "CPU Throttle %"
    }
   ]
  },
  {
   "title": "Network ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"git-server-(.*)$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"git-server-(.*)$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "AIDA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "CPU Used ($interval)",
   "type": "gauge",
   "description": "CPU Utilization",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}[$interval])\n) by (pod)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_start_time_seconds{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (\n  (\n    max \n    (\n      max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-aiservice-([0-9]*)$\"} \n      / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-aiservice-([0-9]*)$\"})\n    )\n  )\n  OR\n  (\n    max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-aiservice-([0-9]*)$\"}\n    / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-aiservice-([0-9]*)$\"})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "bargauge",
   "description": "Low disk space or low inodes count will result in data loss",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-aiservice-[0-9]*\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-aiservice-[0-9]*\"}) / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"([a-z-]*)-aiservice-[0-9]*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ($interval)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}[$interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}) by (pod, container)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of pod memory",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ($interval)",
   "type": "timeseries",
   "description": "CPU usage with throttling percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}[$interval])) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"} [$interval])) / sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"aiservice-([0-9]*)$\", container=\"analytics-ai\"}[$interval])) * 100",
     "legendFormat": "CPU Throttle %"
    }
   ]
  },
  {
   "title": "Network ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"aiservice-(.*)$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"aiservice-(.*)$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}