{
 "title": "Identity Analytics Database",
 "tags": [
  "identity-analytics",
  "database",
  "radiantone"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "operatorNamespace",
    "label": "Operator Namespace",
    "query": {
     "query": "label_values(app=\"database\",namespace)"
    }
   },
   { "name": "namespace", "label": "Database Namespace", "query": { "query": "cnpg_collector_up" } },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "cnpg_collector_up{namespace=\"$namespace\"}"
    }
   },
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "cnpg_collector_up{namespace=\"$namespace\",cluster=~\"$cluster-([1-9][0-9]*)$\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 } },
  { "title": "Health", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 3, "y": 0 } },
  { "title": "Overview", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 7, "y": 0 } },
  { "title": "Storage", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 19, "y": 0 } },
  { "title": "Backups", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 21, "y": 0 } },
  {
   "type": "stat",
   "description": "Cluster Replication Health represents the availability of replica servers available to replace the primary in case of a failure.",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_replication_streaming_replicas{namespace=~\"$namespace\"} - cnpg_pg_replication_is_wal_receiver_up{namespace=~\"$namespace\"})",
     "legendFormat": "Replication"
    }
   ]
  },
  {
   "type": "stat",
   "description": "High lag indicates issue with replication. Network or storage interfaces may not have enough bandwidth to handle incoming traffic and replication at the same time.",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_replication_lag{namespace=~\"$namespace\"}) + max(cnpg_pg_stat_replication_write_lag_seconds{namespace=~\"$namespace\"}) + max(cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\",}) + max(cnpg_pg_stat_replication_replay_lag_seconds{namespace=~\"$namespace\"})",
     "legendFormat": "Lag"
    },
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Low disk space or low inode count will result in data loss.",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"}))) OR (max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"})))",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Last failover",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_postmaster_start_time{namespace=~\"$namespace\"})*1000"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=\"$namespace\"}[15m])) + sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "CPU Utilisation from Requests",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}[5m])\n) by (pod)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "description": "Memory Utilisation from Requests",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_replication_lag{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_write_lag_seconds{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"}))",
     "legendFormat": "DATA"
    },
    {
     "expr": "max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"}))",
     "legendFormat": "WAL"
    },
    {
     "expr": "max(\n    sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n    /\n    sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n    *\n    on(namespace, persistentvolumeclaim) group_left(volume)\n    kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$instances\"}\n)",
     "legendFormat": "Tablespaces (max)"
    }
   ]
  },
  {
   "title": "Last Base Backup",
   "type": "stat",
   "description": "Elapsed time since the last successful base backup.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-(time() - max(cnpg_collector_last_available_backup_timestamp{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "High resource usage (CPU, Memory, DB Connections)",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (max(sum by (cnpg_io_cluster) (cnpg_backends_total{namespace=~\"$namespace\", cnpg_io_cluster=~\"$cluster\"}) / sum by (cnpg_io_cluster) (cnpg_pg_settings_setting{name=\"max_connections\", namespace=~\"$namespace\", cnpg_io_cluster=~\"$cluster\"})))",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Last archived WAL",
   "type": "stat",
   "description": "Computes the time since the last known WAL archival in the primary.\nWe ensure to ignore the metric in the replicas by using (1 - cnpg_pg_replication_in_recovery ) as a multiplicative factor. It will be 0 for replicas, 1 for the primary.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\", service=\"shared-db-metrics\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", service=\"shared-db-metrics\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", service=\"shared-db-metrics\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_postgres_version{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replay Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_replay_lag_seconds{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Base Backups are considered healthy when there has been at least one base backup in the last 24 hours.",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(cnpg_collector_last_available_backup_timestamp{namespace=\"$namespace\"})",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Base Backups are considered healthy when there has been at least one base backup in the last 24 hours.",
   "gridPos": { "h": 2, "w": 1, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\"}))",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Online if there is at least one ready operator pod",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (label_app_kubernetes_io_name) (kube_pod_status_ready{namespace=\"$operatorNamespace\"} * on (pod) group_left( label_app_kubernetes_io_name ) kube_pod_labels{label_app_kubernetes_io_name=~\"cloudnative-pg\"})",
     "legendFormat": "Operator Status"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$RECONCILE_ERRORS_BACKUP + $RECONCILE_ERRORS_CLUSTER * 10 + $RECONCILE_ERRORS_POOLER * 100 + $RECONCILE_ERRORS_SCHEDULED_BACKUP * 1000",
     "type": "math"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",\n  pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}[5m])) by (pod)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Excluding cache",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_database_size_bytes{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "First Recoverability Point",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_collector_first_recoverability_point{namespace=~\"$namespace\"})*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Instance",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Status",
     "type": "text",
     "gridPos": { "h": 1, "w": 2, "x": 3, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Clustering / replicas",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 5, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Zone",
     "type": "text",
     "gridPos": { "h": 1, "w": 2, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 10, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 14, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Wraparound",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 17, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Started",
     "type": "text",
     "gridPos": { "h": 1, "w": 2, "x": 20, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 1, "w": 2, "x": 22, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "repeat": "instances",
     "options": {
      "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$cluster</p>\n  </td>\n</table>"
     },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 9 },
     "repeat": "instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 5, "y": 9 },
     "repeat": "instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\",pod=~\"$instances\"} + cnpg_pg_replication_is_wal_receiver_up{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 1, "x": 7, "y": 9 },
     "repeat": "instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_replication_streaming_replicas{namespace=~\"$namespace\", pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "description": "This metric depends on exporting the: `topology.kubernetes.io/zone` label through kube-state-metrics (not enabled by default). Can be added by changing its configuration with:\n\n```yaml\nmetricLabelsAllowlist:\n  - nodes=[topology.kubernetes.io/zone]\n```",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
     "repeat": "instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_info{namespace=~\"$namespace\"} * on(node,instance) group_left(label_topology_kubernetes_io_zone) kube_node_labels",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 9 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (service) (cnpg_backends_total{namespace=~\"$namespace\"})",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 9 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 * sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\", pod=~\"$instances\"}) / sum by (pod) (cnpg_pg_settings_setting{name=\"max_connections\", namespace=~\"$namespace\", pod=~\"$instances\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "bargauge",
     "description": "Number of transactions from the frozen XID to the current one",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 9 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_pg_database_xid_age{namespace=~\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_postmaster_start_time{namespace=~\"$namespace\"}*1000"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_collector_postgres_version{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Instance",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 3, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 6, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Effective Cache Size",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 9, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 15, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 18, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sequential Page Cost",
     "type": "text",
     "gridPos": { "h": 1, "w": 3, "x": 21, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
     "repeat": "instances",
     "options": {
      "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$cluster</p>\n  </td>\n</table>"
     },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
     "repeat": "instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"max_connections\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"shared_buffers\",namespace=~\"$namespace\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",namespace=~\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"effective_cache_size\",namespace=~\"$namespace\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",namespace=~\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"work_mem\",namespace=~\"$namespace\"} * 1024",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"maintenance_work_mem\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"random_page_cost\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"seq_page_cost\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Configurations",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operational Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",\n  pod=~\"shared-db-([1-9][0-9]*)$\", container=\"postgres\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Session States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(cnpg_backends_total{namespace=~\"$namespace\"}) by (usename)",
       "legendFormat": "total ({{usename}})"
      },
      {
       "expr": "sum(cnpg_backends_total{namespace=~\"$namespace\"}) by (state, usename)",
       "legendFormat": "{{state}} ({{usename}})"
      }
     ]
    },
    {
     "title": "Transactions [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=~\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "committed ({{pod}})"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
       "legendFormat": "rolled back ({{pod}})"
      }
     ]
    },
    {
     "title": "Longest Transaction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_backends_max_tx_duration_seconds{namespace=~\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Deadlocks [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "rate(cnpg_pg_stat_database_deadlocks{datname=\"\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "count ({{pod}})"
      }
     ]
    },
    {
     "title": "Blocked Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "cnpg_backends_waiting_total{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage & I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volume Space Usage: PGDATA and WAL",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"shared-db-([1-9][0-9]*)\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(shared-db-([1-9][0-9]*))-wal\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(shared-db-([1-9][0-9]*))-wal\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Volume Inode Usage: PGDATA and WAL",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Volume Space Usage: Tablespaces",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n/\nsum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n*\non(namespace, persistentvolumeclaim) group_left(volume,pod)\nkube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$instances\"}",
       "legendFormat": "{{volume}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Tuple I/O [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_deleted{datname=\"\",namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "deleted"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_inserted{datname=\"\",namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "inserted"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_fetched{datname=\"\",namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "fetched"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_returned{datname=\"\",namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "returned"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_updated{datname=\"\",namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "updated"
      }
     ]
    },
    {
     "title": "Block I/O [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "rate(cnpg_pg_stat_database_blks_hit{datname=\"\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "hit ({{pod}})"
      },
      {
       "expr": "rate(cnpg_pg_stat_database_blks_read{datname=\"\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "read ({{pod}})"
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max by (datname) (cnpg_pg_database_size_bytes{datname!~\"template.*\",datname!=\"postgres\",namespace=~\"$namespace\"})",
       "legendFormat": " {{pod}}: {{datname}}"
      }
     ]
    },
    {
     "title": "Temp Bytes [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(cnpg_pg_stat_database_temp_bytes{datname=\"\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Ahead Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAL Segment Archive Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "cnpg_collector_pg_wal_archive_status{value=\"ready\",namespace=~\"$namespace\"}",
       "legendFormat": "ready ({{pod}})"
      },
      {
       "expr": "cnpg_collector_pg_wal_archive_status{value=\"done\",namespace=~\"$namespace\"}",
       "legendFormat": "done ({{pod}})"
      }
     ]
    },
    {
     "title": "Archiver Status [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "targets": [
      {
       "expr": "rate(cnpg_pg_stat_archiver_archived_count{namespace=~\"$namespace\"}[5m])",
       "legendFormat": "archived ({{pod}})"
      },
      {
       "expr": "rate(cnpg_pg_stat_archiver_failed_count{namespace=~\"$namespace\"}[5m])",
       "legendFormat": "failed ({{pod}})"
      }
     ]
    },
    {
     "title": "Last Archive Age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\"}",
       "legendFormat": "age ({{pod}})"
      }
     ]
    },
    {
     "title": "WAL Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "cnpg_collector_pg_wal{namespace=~\"$namespace\", value=\"count\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requested/Timed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_bgwriter_checkpoints_req{namespace=~\"$namespace\"} or cnpg_pg_stat_checkpointer_checkpoints_req{namespace=~\"$namespace\"}",
       "legendFormat": "req/{{pod}}"
      },
      {
       "expr": "cnpg_pg_stat_bgwriter_checkpoints_timed{namespace=~\"$namespace\"} or cnpg_pg_stat_checkpointer_checkpoints_timed{namespace=~\"$namespace\"}",
       "legendFormat": "timed/{{pod}}"
      }
     ]
    },
    {
     "title": "Write/Sync time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_bgwriter_checkpoint_write_time{namespace=~\"$namespace\"} or cnpg_pg_stat_checkpointer_write_time{namespace=~\"$namespace\"}",
       "legendFormat": "write/{{pod}}"
      },
      {
       "expr": "cnpg_pg_stat_bgwriter_checkpoint_sync_time{namespace=~\"$namespace\"} or cnpg_pg_stat_checkpointer_sync_time{namespace=~\"$namespace\"}",
       "legendFormat": "sync/{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Collector Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collection Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "cnpg_collector_collection_duration_seconds{namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "cnpg_collector_last_collection_error{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_replication_lag{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Write Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_write_lag_seconds{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    },
    {
     "title": "Flush Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    },
    {
     "title": "Replay Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_replay_lag_seconds{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "First Recoverability Point",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "cnpg_collector_first_recoverability_point{namespace=~\"$namespace\"}*1000 > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}