{
 "title": "Extractor",
 "description": "Dashboard for extractor service",
 "tags": [
  "identity-analytics",
  "extractor",
  "radiantone"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(python_info, radiantlogic_io_environment)"
    }
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": {
     "query": "label_values(python_info{radiantlogic_io_environment=\"$environment\", app=\"extractor-web\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Python Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{implementation}} {{ version }}"
    }
   ]
  },
  {
   "title": "Exporter Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flask_exporter_info{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "App Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "app_info{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "mem - {{instance}}"
    }
   ]
  },
  {
   "title": "Process open fds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "fds"
    }
   ]
  },
  {
   "title": "Garbage Collector Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "python_gc_collections_total{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Garbage Collector Collected Objects",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Garbage Collector Uncollectable Objects",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "HTTP {{ status }} - {{ method }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - percentile 90",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\", status=\"200\", path!=\"/v1.0/healthcheck\"}[$interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - percentile 50",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\", status=\"200\", path!=\"/v1.0/healthcheck\"}[$interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\", status=\"200\", path!=\"/v1.0/healthcheck\"}[$interval])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\", status!=\"200\"}[$interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Average response time [$interval]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\", path!=\"/v1.0/healthcheck\", status=\"200\"}[$interval])\n/\nrate(flask_http_request_duration_seconds_count{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\", path!=\"/v1.0/healthcheck\", status=\"200\"}[$interval])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\", path!=\"/v1.0/healthcheck\", status=\"200\", le=\"0.25\"}[$interval]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{radiantlogic_io_environment=\"$environment\", instance=~\"$instance\", path!=\"/v1.0/healthcheck\", status=\"200\"}[$interval])",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}