{
 "title": "Governance Portal",
 "description": "Dashboard for Governance Portal",
 "tags": [
  "identity-analytics",
  "portal",
  "radiantone"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "environment", "label": "environment", "query": { "query": "label_values(environment)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{app=\"portal\"}, instance)"
    }
   },
   {
    "name": "pod",
    "label": "node",
    "query": {
     "query": "label_values(up{app=\"portal\"}, pod)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{instance=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_info{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tomcat version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_serverinfo{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_availableprocessors{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalphysicalmemorysize{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalswapspacesize{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Session",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalina_manager_activesessions{instance=\"$instance\"} - catalina_manager_rejectedsessions)"
    }
   ]
  },
  {
   "title": "Session created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalina_manager_activesessions{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Session total expired",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalina_manager_rejectedsessions{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Ledger DB Pool usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalina_datasource_idle{instance=\"$instance\", name=\"\\\"jdbc/BRAINWAVEDB\\\"\"} / catalina_datasource_maxactive{instance=\"$instance\", name=\"\\\"jdbc/BRAINWAVEDB\\\"\"} * 100"
    }
   ]
  },
  {
   "title": "Workflow DB Pool usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalina_datasource_idle{instance=\"$instance\", name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"} / catalina_datasource_maxactive{instance=\"$instance\", name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"} * 100"
    }
   ]
  },
  {
   "title": "Audit Logs DB Pool usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalina_datasource_idle{instance=\"$instance\", name=\"\\\"jdbc/BRAINWAVELOGDB\\\"\"} / catalina_datasource_maxactive{instance=\"$instance\", name=\"\\\"jdbc/BRAINWAVELOGDB\\\"\"} * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_operatingsystem_systemcpuload{instance=~\"$instance\"}[5m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",instance=~\"$instance\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Heap /NonHeap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\"}/ ignoring(area) group_left java_lang_operatingsystem_totalphysicalmemorysize{instance=~\"$instance\"} *100",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=~\"$instance\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{instance=~\"$instance\"} * 100",
     "legendFormat": "system"
    },
    {
     "expr": "java_lang_operatingsystem_processcpuload{instance=~\"$instance\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "Current threads"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "Daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=~\"$instance\"}",
     "legendFormat": "Deadlocked threads"
    }
   ]
  },
  {
   "title": "Catalina Manager Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "catalina_manager_activesessions{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "active '{{context}}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "catalina_manager_rejectedsessions{instance=~\"$instance\"}",
     "legendFormat": "rejected '{{context}}'"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Catalina ThreadPool",
   "type": "timeseries",
   "description": "Catalina_readPool_connectionCount /  Catalina_ThreadPool_currentThreadsBusy  /  Catalina_ThreadPool_connectionCount   /   Catalina_ThreadPool_keepAliveCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadcount{instance=\"$instance\"}",
     "legendFormat": "current: {{name}}"
    },
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{instance=\"$instance\"}",
     "legendFormat": "current busy: {{name}}"
    },
    {
     "expr": "tomcat_threadpool_connectioncount{instance=\"$instance\"}",
     "legendFormat": "connection: {{name}}"
    },
    {
     "expr": "tomcat_threadpool_keepalivecount{instance=\"$instance\"}",
     "legendFormat": "keepAlive: {{name}}"
    }
   ]
  },
  {
   "title": "Max Threads",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "catalina_threadpool_maxthreads{instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Min Spare Threads",
   "type": "timeseries",
   "description": "Catalina_ThreadPool_minSpareThreads",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "catalina_threadpool_minsparethreads{instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Accept Count",
   "type": "timeseries",
   "description": "Catalina_ThreadPool_acceptCount",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "catalina_threadpool_acceptcount{instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Poller Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threadpool_pollerthreadcount{instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Catalina Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(catalina_globalrequestprocessor_requestcount_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{protocol}}-{{port}}"
    }
   ]
  },
  {
   "title": "Catalina Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(catalina_globalrequestprocessor_processingtime_total{instance=~\"$instance\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{protocol}}-{{port}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Catalina Request Processor requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "catalina_globalrequestprocessor_requestcount_total{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}} count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "catalina_globalrequestprocessor_errorcount_total{instance=~\"$instance\"}",
     "legendFormat": "{{name}} error"
    }
   ]
  },
  {
   "title": "Catalina Request Processor bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "catalina_globalrequestprocessor_bytesreceived_total{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}} recv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "catalina_globalrequestprocessor_bytessent_total{instance=~\"$instance\"}",
     "legendFormat": "{{name}} sent"
    }
   ]
  },
  {
   "title": "Ledger Connections Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "catalina_datasource_size{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVEDB\\\"\"}",
     "legendFormat": "Current size"
    },
    {
     "expr": "catalina_datasource_active{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVEDB\\\"\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "catalina_datasource_idle{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVEDB\\\"\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Workflow Connections Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "targets": [
    {
     "expr": "catalina_datasource_size{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"}",
     "legendFormat": "Current size"
    },
    {
     "expr": "catalina_datasource_active{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "catalina_datasource_idle{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Audit Logs Connections Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "targets": [
    {
     "expr": "catalina_datasource_size{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVELOGDB\\\"\"}",
     "legendFormat": "Current size"
    },
    {
     "expr": "catalina_datasource_active{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVELOGDB\\\"\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "catalina_datasource_idle{instance=\"$instance\",name=\"\\\"jdbc/BRAINWAVELOGDB\\\"\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Classes loading",
   "type": "timeseries",
   "description": "The number of classes that are currently loaded in the JVM",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{instance=~\"$instance\"}",
     "legendFormat": "Loaded classes"
    },
    {
     "expr": "jvm_classes_unloaded_total{instance=~\"$instance\"}",
     "legendFormat": "Uninstall classes"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\",instance=~\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\",instance=~\"$instance\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\",instance=~\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\",instance=~\"$instance\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC time / 5 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}