{
 "title": "Identity Analytics Service Status",
 "description": "Services availability",
 "tags": [
  "identity-analytics",
  "radiantone"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "clustername",
    "label": "environment",
    "query": {
     "query": "label_values(ia_config_http_status,clustername)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Identity Analytics Services Availability",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Portal",
   "type": "stat",
   "description": "Availability of Governance Portal service",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(ia_portal_http_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(ia_portal_http_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(ia_portal_http_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Portal Availability"
    }
   ]
  },
  {
   "title": "Data Ingestion",
   "type": "stat",
   "description": "Availability of Data Ingestion service",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(ia_batch_http_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(ia_batch_http_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(ia_batch_http_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Configuration Availability"
    }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "Availability of Database",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(ia_database_pg_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(ia_database_pg_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(ia_database_pg_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Database Availability"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "stat",
   "description": "Availability of Controller service",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(ia_controller_http_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(ia_controller_http_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(ia_controller_http_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Controller Availability"
    }
   ]
  },
  {
   "title": "Extractor",
   "type": "stat",
   "description": "Availability of Extractor service",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(ia_extractor_http_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(ia_extractor_http_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(ia_extractor_http_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Extractor Availability"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "stat",
   "description": "Availability of Configuration service",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(ia_config_http_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(ia_config_http_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(ia_config_http_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Configuration Availability"
    }
   ]
  },
  {
   "title": "GIT Sync",
   "type": "stat",
   "description": "Availability of GIT Sync Server",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(ia_git_server_http_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(ia_git_server_http_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(ia_git_server_http_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Configuration Availability"
    }
   ]
  },
  {
   "title": "AIDA",
   "type": "stat",
   "description": "Availability of AI Data Analytics service",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(ia_aida_http_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(ia_aida_http_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(ia_aida_http_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Configuration Availability"
    }
   ]
  },
  {
   "title": "Identity Analytics Service Status",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(ia_aida_http_status{clustername=\"$clustername\"})",
     "legendFormat": "AIDA"
    },
    {
     "expr": "sum(ia_batch_http_status{clustername=\"$clustername\"})",
     "legendFormat": "Data Ingestion"
    },
    {
     "expr": "sum(ia_config_http_status{clustername=\"$clustername\"})",
     "legendFormat": "Configuration"
    },
    {
     "expr": "sum(ia_controller_http_status{clustername=\"$clustername\"})",
     "legendFormat": "Controller"
    },
    {
     "expr": "sum(ia_database_pg_status{clustername=\"$clustername\"})",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(ia_extractor_http_status{clustername=\"$clustername\"})",
     "legendFormat": "Extractor"
    },
    {
     "expr": "sum(ia_git_server_http_status{clustername=\"$clustername\"})",
     "legendFormat": "Git Sync"
    },
    {
     "expr": "sum(ia_portal_http_status{clustername=\"$clustername\"})",
     "legendFormat": "Portal"
    }
   ]
  }
 ]
}