{
 "title": "IDDM Dashboard",
 "description": "Dashboard to monitor key metrics from fid-exporter",
 "tags": [
  "fid",
  "radiantone",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "environment", "query": { "query": "label_values(clustername)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values({clustername=~\"$job\", host_name=~\"fid-.*\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Used",
   "type": "stat",
   "description": "The current amount of system CPU utilized",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_current_system_cpu_utilized_percent{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_current_system_cpu_utilized_percent{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "description": "JVM Memory used(Note: This is not the actual machine memory)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_memory_used_jvm_kilobytes{clustername=~\"$job\", host_name=~\"$node.*\"} / fid_node_monitor_memory_allocated_by_javm_kilobytes{clustername=~\"$job\", host_name=~\"$node.*\"} * 100,\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_memory_used_jvm_kilobytes{cluster_name=~\"$job\", host_name=~\"$node.*\"} / fid_node_monitor_memory_allocated_by_javm_kilobytes{cluster_name=~\"$job\", host_name=~\"$node.*\"} * 100,\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Percent",
   "type": "gauge",
   "description": "Disk space used in percentage",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_disk_space_used_percent{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_disk_space_used_percent{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Space Used (GB)",
   "type": "gauge",
   "description": "Disk space used in GB",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_disk_space_used_bytes{clustername=~\"$job\", host_name=~\"$node.*\"} / 1e+6,\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_disk_space_used_bytes{cluster_name=~\"$job\", host_name=~\"$node.*\"} / 1e+6,\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Physical Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_physical_memory_used_percent{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_physical_memory_used_percent{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_open_file_descriptors_percent{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_open_file_descriptors_percent{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Is Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\nfid_node_monitor_is_this_vds_leader{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\nfid_node_monitor_is_this_vds_leader{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Is Scheduler on Leader",
   "type": "stat",
   "description": "The value is 1 if the ZooKeeper service on the node can be written to. This value is 0 if the ZooKeeper service on the node cannot be written to.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fid_cluster_info_is_task_scheduler_running_on_leader_node{clustername=~\"$job\"}\n or fid_cluster_info_is_task_scheduler_running_on_leader_node{cluster_name=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Number of HDAP Stores",
   "type": "stat",
   "description": "The number of RadiantOne Universal Directory stores on the node.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fid_cluster_info_radiant_one_node_universal_directory_num_stores{clustername=~\"$job\"} or fid_cluster_info_radiant_one_node_universal_directory_num_stores{cluster_name=~\"$job\"} "
    }
   ]
  },
  {
   "title": "Total HDAP Size",
   "type": "stat",
   "description": "The combined index size (in GB) of all RadiantOne Universal Directory (HDAP) stores in the cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fid_cluster_info_radiant_one_cluster_universal_directory_stores_combined_index_size_kilobytes{clustername=~\"$job\"} / 1e+6\n or fid_cluster_info_radiant_one_cluster_universal_directory_stores_combined_index_size_kilobytes{cluster_name=~\"$job\"} / 1e+6"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "description": "Time elapsed since the server is started",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fid_cluster_info_radiant_one_node_uptime_milliseconds{clustername=~\"$job\"} / 1000 or fid_cluster_info_radiant_one_node_uptime_milliseconds{cluster_name=~\"$job\"} / 1000"
    }
   ]
  },
  {
   "title": "Operation Count",
   "type": "stat",
   "description": "The total number of operations RadiantOne FID has done on the connection",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_num_ldap_operations{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_num_ldap_operations{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Live Connections",
   "type": "stat",
   "description": "The live number of concurrent connections to RadiantOne FID (will never be more than connectionMax). This number increases or decreases depending on new connections coming into RadiantOne FID or existing connections being closed",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_num_active_connections{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_num_active_connections{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Peak Stats",
   "type": "stat",
   "description": "Peak values for CPU, Connections, Memory, and Disk Usage",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(fid_node_monitor_highest_system_cpu_utilized_percent{clustername=~\"$job\",host_name=~\"$node.*\"}, \"pod\", \"$1\", \"host_name\", \"(fid-[0-9]+).*\") or label_replace(fid_node_monitor_highest_system_cpu_utilized_percent{cluster_name=~\"$job\",host_name=~\"$node.*\"}, \"pod\", \"$1\", \"host_name\", \"(fid-[0-9]+).*\")",
     "legendFormat": "CPU Peak"
    },
    {
     "expr": "label_replace(fid_node_monitor_num_connections_peak{cluster_name=~\"$job\",host_name=~\"$node.*\"}, \"pod\", \"$1\", \"host_name\", \"(fid-[0-9]+).*\") or label_replace(fid_node_monitor_num_connections_peak{clustername=~\"$job\",host_name=~\"$node.*\"}, \"pod\", \"$1\", \"host_name\", \"(fid-[0-9]+).*\")",
     "legendFormat": "Connections peak"
    },
    {
     "expr": "label_replace(fid_node_monitor_memory_used_peak_kilobytes{cluster_name=~\"$job\",host_name=~\"$node.*\"} / 1048576, \"pod\", \"$1\", \"host_name\", \"(fid-[0-9]+).*\") or label_replace(fid_node_monitor_memory_used_peak_kilobytes{clustername=~\"$job\",host_name=~\"$node.*\"} / 1048576, \"pod\", \"$1\", \"host_name\", \"(fid-[0-9]+).*\")",
     "legendFormat": "Memory Peak"
    },
    {
     "expr": "label_replace(fid_node_monitor_disk_space_used_peak_bytes{cluster_name=~\"$job\",host_name=~\"$node.*\"} / 1e+9, \"pod\", \"$1\", \"host_name\", \"(fid-[0-9]+).*\") or label_replace(fid_node_monitor_disk_space_used_peak_bytes{clustername=~\"$job\",host_name=~\"$node.*\"} / 1e+9, \"pod\", \"$1\", \"host_name\", \"(fid-[0-9]+).*\")",
     "legendFormat": "Disk Peak"
    }
   ]
  },
  {
   "title": "Is ZK Writeable",
   "type": "stat",
   "description": "The value is 1 if the ZooKeeper service on the node can be written to. This value is 0 if the ZooKeeper service on the node cannot be written to.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fid_cluster_info_is_zookeeper_on_node_writable{clustername=~\"$job\"}\n or fid_cluster_info_is_zookeeper_on_node_writable{cluster_name=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Is ZK Readable",
   "type": "stat",
   "description": "The value is 1 if the ZooKeeper service on the node can be written to. This value is 0 if the ZooKeeper service on the node cannot be written to.",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fid_cluster_info_is_zookeeper_on_node_readable{clustername=~\"$job\"}\n or fid_cluster_info_is_zookeeper_on_node_readable{cluster_name=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Is ZK ReadOnly",
   "type": "stat",
   "description": "The value is 1 if the ZooKeeper service on the node can be written to. This value is 0 if the ZooKeeper service on the node cannot be written to.",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fid_cluster_info_is_zookeeper_on_node_read_only{clustername=~\"$job\"}\n or fid_cluster_info_is_zookeeper_on_node_read_only{cluster_name=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_average_system_cpu_utilized_percent{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_average_system_cpu_utilized_percent{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_memory_used_max_percent{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_memory_used_max_percent{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_disk_space_used_percent{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_disk_space_used_percent{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  fid_node_monitor_num_active_connections{cluster_name=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n) or \nlabel_replace(\n  fid_node_monitor_num_active_connections{clustername=~\"$job\", host_name=~\"$node.*\"},\n  \"pod\",\n  \"$1\",\n  \"host_name\",\n  \"(fid-[0-9]+).*\"\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}