{
 "title": "Service Status",
 "tags": [
  "fid",
  "radiantone"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "clustername",
    "label": "environment",
    "query": {
     "query": "label_values(fid_ldap_status,clustername)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "LDAPS Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(fid_ldaps_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(fid_ldaps_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(fid_ldaps_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "LDAPS Availability"
    }
   ]
  },
  {
   "title": "REST Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(fid_https_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(fid_https_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(fid_https_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "REST Availability"
    }
   ]
  },
  {
   "title": "Control Panel Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(fid_cp_https_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(fid_cp_https_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(fid_cp_https_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Control Panel Availability"
    }
   ]
  },
  {
   "title": "Admin Service Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(fid_admin_https_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(fid_admin_https_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(fid_admin_https_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Admin Service Availability"
    }
   ]
  },
  {
   "title": "Zookeeper Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(fid_zk_status{clustername=\"$clustername\"}[$__range])) - sum(sum_over_time(fid_zk_status{clustername=\"$clustername\"}[$__range])))/sum(count_over_time(fid_zk_status{clustername=\"$clustername\"}[$__range])) * 100",
     "legendFormat": "Zookeeper Availability"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(fid_ldaps_status{clustername=\"$clustername\"})",
     "legendFormat": "LDAPS Service"
    },
    {
     "expr": "sum(fid_https_status{clustername=\"$clustername\"})",
     "legendFormat": "REST Service"
    },
    {
     "expr": "sum(fid_cp_https_status{clustername=\"$clustername\"})",
     "legendFormat": "Control Panel"
    },
    {
     "expr": "sum(fid_admin_https_status{clustername=\"$clustername\"})",
     "legendFormat": "Admin Service"
    },
    {
     "expr": "sum(fid_zk_status{clustername=\"$clustername\"})",
     "legendFormat": "Zookeeper"
    }
   ]
  }
 ]
}