apiVersion: v1
data:
  {{- if .Values.zk.external }}
  ZK: "external"
  {{- end }}
  ZK_CONN_STR: {{ .Values.zk.connectionString | quote }} #this should match the service name from zk deployment
  ZK_CLUSTER: {{ .Values.zk.clusterName | quote }}
  {{- if .Values.fid.readonly }}
  NODE_TYPE: "follower"
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    role: fid
  name: {{ template "fid.fullname" . }}
  labels:
    app: {{ template "fid.fullname" . }}
    chart: "{{ template "fid.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  
