apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    {{- include "fid.labels" . | nindent 4 }}
    app.kubernetes.io/core-name: {{ include "fid.name" . }}
data:
  fluent.conf: |
    {{- if semverCompare ">1.0.0" .Chart.Version }}
    # Configuration for Helm chart version > 1.0.0
    {{- $elasticSearchHost := .Values.metrics.fluentd.elasticSearchHost }}
    {{- $aggregators := .Values.metrics.fluentd.aggregators }}
    {{ $clusterName := .Values.zk.clusterName }}
    {{- range $key, $val := .Values.metrics.fluentd.logs }}
      {{- if $val.enabled }}
        <source>
          @type tail
          read_from_head true
          path {{ $val.path }}
          pos_file {{ $val.path }}.pos
          tag {{ $val.index }}
          {{- if $val.parse }}
          {{- $val.parse | nindent 10 }}
          {{- else }}
          format multiline
          format_firstline /\d{4}-\d{1,2}-\d{1,2}/
          format1 /^(?<message>.*)$/
          {{- end }}
        </source>
        <filter {{ $val.index }}>
          @type record_transformer
          <record>
            hostname ${hostname}
            clustername {{ $clusterName }}
          </record>
        </filter>
        <match {{ $val.index }}>
          @type copy
          {{- if gt (len $aggregators) 0 }}
            {{- range $aggregators }}
              <store>
                @type {{ .type }}
                {{- if eq .type "splunk_hec" }}
                hec_host {{ .hec_hostname }}
                hec_port {{ .hec_port }}
                hec_token {{ .hec_token }}
                insecure_ssl true
                index {{ $val.index }}
                {{- else }}
                host {{ .host }}
                port {{ .port }}
                logstash_format true
                logstash_prefix {{ $val.index }}
                {{- end }}
              </store>
            {{- end }}
          {{- else if $elasticSearchHost }}
            <store>
              @type elasticsearch
              host {{ $elasticSearchHost }}
              port "9200"
              logstash_format true
              logstash_prefix {{ $val.index }}
            </store>
          {{- end }}
        </match>
      {{- end }}
    {{- end }}
    {{- end }}
