{{- if .Values.metrics.fluentd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    {{- include "fid.labels" . | nindent 4 }}
    app.kubernetes.io/core-name: {{ include "fid.name" . }}
data:
  fluent.conf: |
    {{- $elasticSearchHost := .Values.metrics.fluentd.elasticSearchHost }}
    {{- $aggregators := .Values.metrics.fluentd.aggregators | default list }}
    {{- $clusterName := .Values.zk.clusterName | default "fid-cluster" }}
    {{- range $logName, $val := .Values.metrics.fluentd.logs }}
      {{- if $val.enabled }}
        {{- $index := (default $val.index $val.custom_index) }}
        {{- $splunkIndex := (default (trimSuffix ".log" $index) $val.splunk_index) }}
        <source>
          @type tail
          read_from_head true
          path {{ $val.path }}
          pos_file {{ $val.path }}.pos
          tag {{ $logName }}.log
          {{- if $val.parse }}
          {{- $val.parse | nindent 10 }}
          {{- else }}
          format multiline
          format_firstline /\d{4}-\d{1,2}-\d{1,2}/
          format1 /^(?<message>.*)$/
          {{- end }}
        </source>
        <filter {{ $logName }}.log>
          @type record_transformer
          <record>
            hostname ${hostname}
            clustername {{ $clusterName }}
          </record>
        </filter>
        <match {{ $logName }}.log>
          @type copy
          {{- if gt (len $aggregators) 0 }}
          {{- range $aggregator := $aggregators }}
          <store>
            @type {{ $aggregator.type }}
            {{- range $key, $value := $aggregator }}
            {{- if and (ne $key "type") (ne $key "source") (ne $key "sourcetype") }}
            {{ $key }} {{ $value }}
            {{- end }}
            {{- end }}
            {{- if eq $aggregator.type "splunk_hec" }}
            index {{ $splunkIndex }}
            {{- if $val.splunk_source }}
            source {{ $val.splunk_source }}
            {{- else if $aggregator.source }}
            source {{ $aggregator.source }}
            {{- end }}
            {{- if $val.splunk_sourcetype }}
            sourcetype {{ $val.splunk_sourcetype }}
            {{- else if $aggregator.sourcetype }}
            sourcetype {{ $aggregator.sourcetype }}
            {{- end }}
            {{- else }}
            logstash_prefix {{ $index }}
            logstash_format true
            {{- end }}
          </store>
          {{- end }}
          {{- else if $elasticSearchHost }}
          <store>
            @type elasticsearch
            host {{ $elasticSearchHost }}
            port 9200
            logstash_format true
            logstash_prefix {{ $index }}
          </store>
          {{- end }}
        </match>
      {{- end }}
    {{- end }}
{{- end }}
