{{- if .Values.metrics.fluentd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    {{- include "fid.labels" . | nindent 4 }}
    app.kubernetes.io/core-name: {{ include "fid.name" . }}
data:
  fluent.conf: |
    {{- $elasticSearchHost := .Values.metrics.fluentd.elasticSearchHost }}
    {{- $aggregators := .Values.metrics.fluentd.aggregators | default list }}
    {{- $clusterName := .Values.zk.clusterName | default "fid-cluster" }}
    {{- range $key, $val := .Values.metrics.fluentd.logs }}
      {{- if $val.enabled }}
        {{- $index := (default $val.index $val.custom_index) }}
        {{- $indexForSplunk := (trimSuffix ".log" (default $val.index $val.custom_index)) }}
        <source>
          @type tail
          read_from_head true
          path {{ $val.path }}
          pos_file {{ $val.path }}.pos
          tag {{ $index }}
          {{- if $val.parse }}
          {{- $val.parse | nindent 10 }}
          {{- else }}
          format multiline
          format_firstline /\d{4}-\d{1,2}-\d{1,2}/
          format1 /^(?<message>.*)$/
          {{- end }}
        </source>
        <filter {{ $index }}>
          @type record_transformer
          <record>
            hostname ${hostname}
            clustername {{ $clusterName }}
          </record>
        </filter>
        <match {{ $index }}>
          @type copy
          {{- if gt (len $aggregators) 0 }}
            {{- range $aggregators }}
            <store>
              @type {{ .type }}
              {{- if eq .type "splunk_hec" }}
              hec_host {{ .hec_hostname }}
              hec_port {{ .hec_port }}
              hec_token {{ .hec_token }}
              insecure_ssl true
              index {{ $indexForSplunk }}
              {{- else }}
              host {{ .host }}
              port {{ .port }}
              logstash_format true
              logstash_prefix {{ $index }}
              {{- if .user }}
              user {{ .user }}
              {{- end }}
              {{- if .password }}
              password {{ .password }}
              {{- end }}
              {{- if .ssl_verify }}
              ssl_verify  {{ .ssl_verify }}
              {{- end }}
              {{- if .ca_file }}
              ca_file {{ .ca_file }}
              {{- end }}
              {{- if .scheme }}
              scheme {{ .scheme }}
              {{- end }}
              {{- end }}
            </store>
            {{- end }}
          {{- else if $elasticSearchHost }}
            <store>
              @type elasticsearch
              host {{ $elasticSearchHost }}
              port "9200"
              logstash_format true
              logstash_prefix {{ $index }}
            </store>
          {{- end }}
        </match>
      {{- end }}
    {{- end }}
{{- end }}
