{{- if hasKey .Values.fid "followerOnly" }}
{{- if and (.Values.fid.followerOnly.enabled) ((.Values.fid.followerOnly.autoscaling).enabled | default false) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fid.fullname" . }}
  labels:
    {{- include "fid.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "5"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "fid.fullname" . }}-follower
  minReplicas: {{ .Values.fid.followerOnly.minReplicas }}
  maxReplicas: {{ .Values.fid.followerOnly.maxReplicas }}
  metrics:
  {{- if .Values.fid.followerOnly.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.fid.followerOnly.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.fid.followerOnly.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.fid.followerOnly.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
{{- end }}
