apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fid.fullname" . }}-hook-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fid.fullname" . }}-manage-pods
  #namespace: <namespace_name> 
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - pods
      - pods/exec
    verbs:
      - get
      - list
      - delete
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fid.fullname" . }}-manage-pods
subjects:
- kind: ServiceAccount
  name: {{ include "fid.fullname" . }}-hook-account
roleRef:
  kind: Role
  name: {{ include "fid.fullname" . }}-manage-pods
  apiGroup: rbac.authorization.k8s.io

