{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fid.fullname" . }}
  labels:
    {{- include "fid.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "fid.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetLDAPConnectionCount }}
    - type: Object
      object:
        target:
          apiVersion: extensions/v1beta1
          kind: Job
          name: tests1
        targetValue: {{ .Values.autoscaling.targetLDAPConnectionCount}}
        metricName: avg(ldap_connection_count)
    # - type: Object
    #   object:
    #     metric:
    #       name: ldap_connection_count
    #       describedObject:
    #         apiVersion: batch/v1
    #         kind: Job
    #         name: tests
    #       target:
    #         kind: Value
    #         value: {{ .Values.metrics.targetLDAPConnectionCount}}
  {{- end }}
{{- end }}
