{{- if .Values.imageCredentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    {{- include "fid.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}{{ toYaml . | nindent 4 }}{{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
