{{- if and (not .Values.fid.sealedSecrets) (not .Values.sealedSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: rootcreds-{{ template "fid.fullname" . }}
  labels:
    app: {{ template "fid.fullname" . }}
    chart: "{{ template "fid.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.fid.rootUser }}
  fid-root-username: {{ .Values.fid.rootUser | b64enc | quote }}
  {{- end }}
  {{- if .Values.fid.rootPassword }}
  fid-root-password: {{ .Values.fid.rootPassword | b64enc | quote }}
  {{- else }}
  fid-root-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- if .Values.zk.userName }}
  zk-username: {{ .Values.zk.userName | b64enc | quote }}
  {{- end }}
  {{- if .Values.zk.password }}
  zk-password: {{ .Values.zk.password | b64enc | quote }}
  {{- else }}
  zk-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- if .Values.fid.license }}
  fid-license: {{ .Values.fid.license | b64enc | quote }}
  {{- end }}
{{- end }}
