{{- if eq .Values.kibana.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-data
data:

  curl-script.sh: |
    #!/bin/sh

    function import_index {
        echo "Importing Index-Patterns"
        echo "The curl command creates symlinks so using an alternative method"
        echo "Copying the Index-Pattern file from /kibana/index_pattern to /opt/index_pattern to make it hardlink"
        cat /kibana/index_pattern.ndjson > /opt/index_pattern.ndjson
        response=""
        success="false"
        until [[ "$success" == "true" ]]; do
            response=$(curl -s --location --request POST "${KIBANA_URL}/api/saved_objects/_import?overwrite=true" \
                            --header 'kbn-xsrf: true' \
                            --form 'file=@"/opt/index_pattern.ndjson"' | jq '.')
            success=$(echo "$response" | jq -r '.success')
            echo "Response: $response"
            sleep 5
        done
        if [[ "$success" == "true" ]]; then
            printf "\nThe Kibana Index Patterns have been successfully imported\n"
        else
            printf "\nFailure while importing index-pattern\n"
            echo "Details: $(echo "$response" | jq '.errors[]')"
        fi
    }

    while true
    do
      if [[ $(curl -s ${KIBANA_URL}/api/status | jq -r .status.overall.state) == "green" ]]; then
        echo "kibana is healthy"
        import_index
        break
      else
        echo "kibana is unhealthy"
      fi
    sleep 5
    done

  index_pattern.ndjson: |
{{ .Files.Get "dashboards/kibana-index-pattern.ndjson" | indent 4 }}


{{- end }}

