{{- if eq .Values.kibana.enabled true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-import
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 600
  template:
    spec:
      {{- with .Values.kibana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      volumes:
      - name: kibana-data
        configMap:
          name: kibana-data
          defaultMode: 0777
      # initContainers:
      # - name: wait-for-kibana
      #   image: curlimages/curl:latest
      #   command:
      #   - 'sh'
      #   - '-c'
      #   - |
      #     until curl -s -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}" "${KIBANA_URL}/api/status" | grep -q '"status":{"overall":{"state":"green"'; do
      #       echo "Waiting for Kibana to be ready...";
      #       sleep 10;
      #     done
      containers:
      - name: kibana-import
        image: alpine/curl:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KIBANA_URL
          value: "http://{{ .Values.kibana.fullnameOverride | default "kibana" }}.{{ .Release.Namespace }}.svc.cluster.local:5601{{ .Values.kibana.healthCheckPath | default "/kibana" }}"
        {{- $username := "" }}
        {{- $password := "" }}
        {{- range .Values.kibana.extraEnvs }}
        {{- if eq .name "ELASTICSEARCH_USERNAME" }}
        {{- $username = .value }}
        {{- end }}
        {{- if eq .name "ELASTICSEARCH_PASSWORD" }}
        {{- $password = .value }}
        {{- end }}
        {{- end }}
        {{- if and $username $password }}
        - name: ELASTICSEARCH_USERNAME
          value: {{ $username | quote }}
        - name: ELASTICSEARCH_PASSWORD
          value: {{ $password | quote }}
        - name: AUTH_ENABLED
          value: "true"
        {{- else }}
        - name: AUTH_ENABLED
          value: "false"
        {{- end }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add -q --no-cache jq
          /kibana/curl-script.sh
        volumeMounts:
        - name: kibana-data
          mountPath: /kibana/
{{- end }}
