{{- if index .Values "cloudnative-pg" "enabled" }}
{{- $cnpgDependency := include "common-services.getDependency" (dict "name" "cloudnative-pg" "context" .) | fromJson -}}
{{- $cnpgRepository := $cnpgDependency.repository -}}
{{- $cnpgVersion := $cnpgDependency.version -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: cnpg-crds-installer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded,BeforeHookCreation
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: cnpg-crd-job
      restartPolicy: OnFailure
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: install-crds
          image: alpine:3.20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          command:
            - /bin/sh
            - -c
            - |
              set -e
              apk add --no-cache curl tar helm kubectl yq-go
              helm repo add cnpg {{ $cnpgRepository | quote }}
              helm repo update
              # 'helm show crds' is not working with CNPG because CRDs are located in the templates/crds directory
              # helm show crds cloudnative-pg/cloudnative-pg --version {{ $cnpgVersion }} > crds.yaml
              helm template cnpg cnpg/cloudnative-pg --include-crds --version {{ $cnpgVersion }} > /tmp/rendered.yaml
              yq e 'select(.kind == "CustomResourceDefinition")' /tmp/rendered.yaml > /tmp/crds.yaml
              # remove the last-applied-configuration annotation from the CRDs
              for crd in $(kubectl get crd -o name | grep '\.postgresql\.cnpg\.io'); do
                kubectl annotate $crd kubectl.kubernetes.io/last-applied-configuration- || true
              done
              kubectl --server-side --force-conflicts apply -f /tmp/crds.yaml
{{- end }}
