{{- if index .Values "cloudnative-pg" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: cnpg-operator-metrics
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: monitoring
    app: database
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cloudnative-pg
{{- end }}
