{
 "title": "IDO - Alert center",
 "tags": [
  "identity-observability",
  "alert-center",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{app_kubernetes_io_component=\"alert-center\"},radiantlogic_io_environment)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Configured alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nb_alerts{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\", type=\"observation\"}",
     "legendFormat": "Observations"
    },
    {
     "expr": "nb_alerts{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\", type=\"control\"}",
     "legendFormat": "Controls"
    }
   ]
  },
  {
   "title": "Processed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nb_processed_obs_total{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "Observations"
    },
    {
     "expr": "nb_processed_ctrl_total{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "Controls"
    }
   ]
  },
  {
   "title": "Incoming messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nb_incoming_total{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "Number"
    },
    {
     "expr": "size_incoming_total{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Pending alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nb_pending_alerts{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "Number"
    },
    {
     "expr": "size_pending_alerts{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Sent alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nb_alerts_sent_total{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\", service=\"email\"}",
     "legendFormat": "emails"
    },
    {
     "expr": "nb_alerts_sent_total{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\", service=\"webhook\"}",
     "legendFormat": "WebHooks"
    },
    {
     "expr": "nb_alerts_sent_total{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\", service=\"slack\"}",
     "legendFormat": "Slack"
    },
    {
     "expr": "nb_alerts_sent_total{app_kubernetes_io_component=\"alert-center\", radiantlogic_io_environment=\"$environment\", service=\"msteams\"}",
     "legendFormat": "MS Teams"
    }
   ]
  }
 ]
}