{
 "title": "IDO - Graph Database",
 "tags": [
  "nebula",
  "monitoring",
  "identity-observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(nebula_metad_count, radiantlogic_io_environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nebula_metad_count{radiantlogic_io_environment=\"$environment\"}, app_kubernetes_io_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number Of Metad Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nebula_metad_count{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number Of Graphd Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nebula_graphd_count{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number Of Storaged Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nebula_storaged_count{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number  Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nebula_graphd_num_queries_rate_5{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} rate"
    },
    {
     "expr": "nebula_graphd_num_queries_sum_5{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} sum"
    }
   ]
  },
  {
   "title": "Number Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nebula_graphd_num_query_errors_rate_60{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} rate"
    },
    {
     "expr": "nebula_graphd_num_query_errors_sum_60{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} sum"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nebula_graphd_query_latency_us_avg_5{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} avg"
    },
    {
     "expr": "nebula_graphd_query_latency_us_p95_5{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} p95"
    }
   ]
  },
  {
   "title": "Number Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nebula_graphd_num_slow_queries_rate_5{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} rate"
    },
    {
     "expr": "nebula_graphd_num_slow_queries_sum_5{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} sum"
    }
   ]
  },
  {
   "title": "Slow Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nebula_graphd_slow_query_latency_us_avg_5{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} avg"
    },
    {
     "expr": "nebula_graphd_slow_query_latency_us_p95_5{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_cluster=\"$cluster\"}",
     "legendFormat": "{{instanceName}} p95"
    }
   ]
  }
 ]
}