{
 "title": "IDO Graph Pipeline Sources",
 "description": "Only source graphs",
 "tags": [
  "monitoring",
  "identity-observability",
  "graph-pipeline"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source_var", "label": "Source", "query": { "query": "label_values(source)" } },
   {
    "name": "operation_var",
    "label": "Operation",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_operator_source_operation_rt_events_counter,operation)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "$source_var", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(source, operation) (flink_taskmanager_job_task_operator_source_operation_rt_events_counter{source=~\"$source_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{source}} {{operation}}"
    }
   ]
  },
  {
   "title": "Vertices count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(source, operation) (flink_taskmanager_job_task_operator_source_operation_rt_events_vertex_counter{source=~\"$source_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{source}} {{operation}}"
    }
   ]
  },
  {
   "title": "Edges count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(source, operation) (flink_taskmanager_job_task_operator_source_operation_rt_events_edge_counter{source=~\"$source_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{source}} {{operation}}"
    }
   ]
  },
  {
   "title": "Events rate/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(source, operation) (rate(flink_taskmanager_job_task_operator_source_operation_rt_events_counter{source=~\"$source_var\", operation=~\"$operation_var\"}[5m]))",
     "legendFormat": "{{source}} {{operation}} events rate/s "
    }
   ]
  },
  {
   "title": "Vertices output per event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_source_operation_rt_events_vertex_counter{source=~\"$source_var\", operation=~\"$operation_var\"}[5m])) / clamp_min(sum(rate(flink_taskmanager_job_task_operator_source_operation_rt_events_counter{source=~\"$source_var\", operation=~\"$operation_var\"}[5m])), 1)",
     "legendFormat": "Vertices output per event"
    }
   ]
  },
  {
   "title": "Edges output per event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_source_operation_rt_events_edge_counter{source=~\"$source_var\", operation=~\"$operation_var\"}[5m])) / clamp_min(sum(rate(flink_taskmanager_job_task_operator_source_operation_rt_events_counter{source=~\"$source_var\", operation=~\"$operation_var\"}[5m])), 1)",
     "legendFormat": "Edges output per event"
    }
   ]
  },
  {
   "title": "Transformation time ms",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg by(source, operation) (flink_taskmanager_job_task_operator_source_operation_rt_events_proc_time{source=~\"$source_var\", operation=~\"$operation_var\", quantile=\"0.5\"})",
     "legendFormat": "{{source}} {{operation}} quantile_0.5 "
    },
    {
     "expr": "avg by(source, operation) (flink_taskmanager_job_task_operator_source_operation_rt_events_proc_time{source=~\"$source_var\", operation=~\"$operation_var\", quantile=\"0.75\"})",
     "legendFormat": "{{source}} {{operation}} quantile_0.75 "
    },
    {
     "expr": "avg by(source, operation) (flink_taskmanager_job_task_operator_source_operation_rt_events_proc_time{source=~\"$source_var\", operation=~\"$operation_var\", quantile=\"0.95\"})",
     "legendFormat": "{{source}} {{operation}} quantile_0.95 "
    },
    {
     "expr": "avg by(source, operation) (flink_taskmanager_job_task_operator_source_operation_rt_events_proc_time{source=~\"$source_var\", operation=~\"$operation_var\", quantile=\"0.99\"})",
     "legendFormat": "{{source}} {{operation}} quantile_0.99 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_source_operation_rt_events_error_counter{source=~\"$source_var\", operation=~\"$operation_var\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_source_operation_rt_events_uuid_missing_rejected_counter{source=~\"$source_var\", operation=~\"$operation_var\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}