{
 "title": "IDO Graph Pipeline Sinks",
 "tags": [
  "monitoring",
  "identity-observability",
  "graph-pipeline"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source_var", "label": "Source", "query": { "query": "label_values(source)" } },
   {
    "name": "operation_var",
    "label": "Operation",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_operator_source_operation_rt_events_counter,operation)"
    }
   },
   {
    "name": "entity_var",
    "label": "Entity",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_operator_source_operation_entity_rt_graph_events_counter_output,entity)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Events for entities $entity_var",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Events Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(source, entity) (flink_taskmanager_job_task_operator_source_operation_entity_rt_graph_events_counter_output{entity=~\"$entity_var\", source=~\"$source_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{source}} to {{entity}}"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg by(source, entity) (flink_taskmanager_job_task_operator_source_operation_entity_rt_events_output_batch_size{entity=~\"$entity_var\", source=~\"$source_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{source}} to {{entity}}"
    }
   ]
  },
  {
   "title": "Batch Errors",
   "type": "timeseries",
   "description": "Batch errors counted per entity/operation combinations, not including source",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(entity, operation) (flink_taskmanager_job_task_operator_operation_entity_rt_events_batch_error_counter_output{entity=~\"$entity_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{entity}} {{operation}}"
    }
   ]
  },
  {
   "title": "Event Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(source, entity) (flink_taskmanager_job_task_operator_source_operation_entity_rt_graph_events_error_counter_output{entity=~\"$entity_var\", source=~\"$source_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{source}} to {{entity}}"
    }
   ]
  },
  {
   "title": "Retries Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(source, entity) (flink_taskmanager_job_task_operator_source_operation_entity_rt_graph_events_retry_counter_output{entity=~\"$entity_var\", source=~\"$source_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{source}} to {{entity}} "
    }
   ]
  },
  {
   "title": "Batch Retries",
   "type": "timeseries",
   "description": "Batch retries counted per entity/operation combinations, not including source",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(entity, operation) (flink_taskmanager_job_task_operator_operation_entity_rt_events_batch_retry_counter_output{entity=~\"$entity_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{entity}} {{operation}}"
    }
   ]
  },
  {
   "title": "Sink Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(source, entity) (flink_taskmanager_job_task_operator_source_operation_entity_rt_events_output_proc_time{entity=~\"$entity_var\", source=~\"$source_var\", operation=~\"$operation_var\"})",
     "legendFormat": "{{source}} to {{entity}}"
    }
   ]
  }
 ]
}