{
 "title": "IDO - Portal Dashboards",
 "description": "General overview",
 "tags": [
  "monitoring",
  "identity-observability",
  "ido-dashboard"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(radiantlogic_io_environment)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "cnpg_collector_up{cluster=\"analytics-db\", service=\"analytics-db-metrics\", radiantlogic_io_environment=\"$environment\"}"
    }
   },
   { "name": "interval", "label": "interval", "query": "5m,15m,30m,1h,6h,12h,1d" },
   {
    "name": "portal_instance",
    "label": "portal_instance",
    "query": {
     "query": "label_values(up{radiantlogic_io_environment=\"$environment\", app=\"portal\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used ($interval)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"}[$interval])\n) by (pod, container)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"}\n) by (pod, container)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (cnpg_backends_total{radiantlogic_io_environment=~\"$environment\", service=\"analytics-db-metrics\"}) / sum(cnpg_pg_settings_setting{name=\"max_connections\", radiantlogic_io_environment=~\"$environment\", service=\"analytics-db-metrics\"})",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Storage usage",
     "type": "bargauge",
     "description": "Low disk space or low inodes count will result in data loss",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)$\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)$\"}) / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)$\"}",
       "legendFormat": "DATA"
      },
      {
       "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)-wal\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)-wal\"}) / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)-wal\"}",
       "legendFormat": "WAL"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_start_time_seconds{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)\", container=\"postgres\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)\", container=\"postgres\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Analytics DB size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (datname) (cnpg_pg_database_size_bytes{radiantlogic_io_environment=\"$environment\", datname=\"analytics_db\", service=\"analytics-db-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shared DB size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (datname) (cnpg_pg_database_size_bytes{radiantlogic_io_environment=\"$environment\", datname=\"shared_db\", service=\"analytics-db-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current ($interval)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"}[$interval]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"}) by (pod)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage",
     "type": "stat",
     "description": "Low disk space or low inodes count will result in data loss",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max (\n  (\n    max \n    (\n      max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)([a-z-]*)\"} \n      / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)([a-z-]*)\"})\n    )\n  )\n  OR\n  (\n    max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)([a-z-]*)\"}\n    / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)([a-z-]*)\"})\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage usage size",
     "type": "stat",
     "description": "Low disk space or low inodes count will result in data loss",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)$\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)$\"})",
       "legendFormat": "DATA"
      },
      {
       "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)-wal\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"analytics-db-([1-9][0-9]*)-wal\"})",
       "legendFormat": "WAL"
      }
     ]
    },
    {
     "title": "Archived",
     "type": "stat",
     "description": "Last WAL archived",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\", service=\"analytics-db-metrics\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", service=\"analytics-db-metrics\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", service=\"analytics-db-metrics\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "stat",
     "description": "Number of deadlocks detected in Analytics DB over 5 minutes",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_database_deadlocks{namespace=\"$namespace\", datname=\"analytics_db\", service=\"analytics-db-metrics\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "description": "Total number of pod memory",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)$\", container=\"postgres\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocked",
     "type": "stat",
     "description": "Total number of backends that are currently waiting on other queries",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_backends_waiting_total{namespace=\"$namespace\", service=\"analytics-db-metrics\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "bargauge",
     "description": "Number of transactions from the frozen XID to the current one",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_pg_database_xid_age{namespace=\"$namespace\", datname=\"analytics_db\", service=\"analytics-db-metrics\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk I/O Utilization ($interval)",
     "type": "timeseries",
     "description": "The disk I/O utilization metrics are bytes written and read.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)\", container=\"postgres\"}[$interval]))",
       "legendFormat": "Writes"
      },
      {
       "expr": "sum by (interface) (rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"analytics-db-([1-9][0-9]*)\", container=\"postgres\"}[$interval]))",
       "legendFormat": "Reads"
      }
     ]
    },
    {
     "title": "Network ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"analytics-db-([0-9]*)$\"}[$interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"analytics-db-([0-9]*)$\"}[$interval]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  { "title": "Governance Portal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Used ($interval)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}[$interval])\n) by (pod)\n/ sum(\n  container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"} \n  / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}) by (pod)\n/ \nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"portal\",area=\"heap\"} / jvm_memory_bytes_max{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ledger DB Pool Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalina_datasource_idle{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\", name=\"\\\"jdbc/BRAINWAVEDB\\\"\"} / catalina_datasource_maxactive{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\", name=\"\\\"jdbc/BRAINWAVEDB\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\"} - tomcat_session_expiredsessions_total)",
     "legendFormat": "Current count"
    },
    {
     "expr": "sum(tomcat_session_sessioncounter_total{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\"})",
     "legendFormat": "Total created"
    },
    {
     "expr": "sum(tomcat_session_expiredsessions_total{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\"})",
     "legendFormat": "Total expired"
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{radiantlogic_io_environment=~\"$environment\", app_kubernetes_io_component=\"portal\"}",
     "legendFormat": "Current threads"
    },
    {
     "expr": "jvm_threads_daemon{radiantlogic_io_environment=~\"$environment\", app_kubernetes_io_component=\"portal\"}",
     "legendFormat": "Daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{radiantlogic_io_environment=~\"$environment\", app_kubernetes_io_component=\"portal\", instance=\"$portal_instance\"}",
     "legendFormat": "Deadlocked threads"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\"})*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ($interval)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "description": "Last Java heap measured while data ingestion ran",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow DB Pool usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalina_datasource_idle{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\", name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"} / catalina_datasource_maxactive{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\", name=\"\\\"jdbc/BRAINWAVEWORKFLOWDB\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"portal-(.*)$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"portal-(.*)$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"} / container_spec_cpu_period{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of pod memory",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"portal-([0-9]*)$\", container=\"portal\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total heap memory available",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{app_kubernetes_io_component=\"portal\", radiantlogic_io_environment=\"$environment\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ($interval)",
   "type": "timeseries",
   "description": "CPU usage with throttling percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}[$interval]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"} [$interval])) / sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"portal-(.*)$\", container=\"portal\"}[$interval]))",
     "legendFormat": "CPU Throttle %"
    }
   ]
  },
  {
   "title": "Tomcat Request Processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "catalina_globalrequestprocessor_bytesreceived_total{radiantlogic_io_environment=\"$environment\", port=\"8080\"}",
     "legendFormat": "received"
    },
    {
     "expr": "catalina_globalrequestprocessor_bytessent_total{radiantlogic_io_environment=\"$environment\", port=\"8080\"}",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}