{
 "title": "IDO - Observations - Process",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "tags": [
  "monitoring",
  "identity-observability",
  "supervisor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{app_kubernetes_io_component=\"observation-supervisor\"}, radiantlogic_io_environment)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Resident memory"
    },
    {
     "expr": "process_virtual_memory_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Memory change rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}[$interval])",
     "legendFormat": "Resident memory"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}[$interval])",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Memstats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}[1m])",
     "legendFormat": "Allocation rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Heap inuse"
    }
   ]
  },
  {
   "title": "Memstats change rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}[$interval])",
     "legendFormat": "Bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}[$interval])",
     "legendFormat": "Allocation rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}[$interval])",
     "legendFormat": "Stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}[$interval])",
     "legendFormat": "Heap inuse"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "FDs"
    }
   ]
  },
  {
   "title": "Open FDs change rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(process_open_fds{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}[$interval])",
     "legendFormat": "FDs change"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "{{quantile}} quantile"
    }
   ]
  }
 ]
}