{
 "title": "IDO - Observations - Channels contention",
 "tags": [
  "monitoring",
  "identity-observability",
  "supervisor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{app_kubernetes_io_component=\"observation-supervisor\"}, radiantlogic_io_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Observation changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "stats_channel_obs_change_cap{otel_scope_name=\"supervisor\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "stats_channel_obs_change_len{otel_scope_name=\"supervisor\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Markers changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "stats_channel_mrk_change_cap{otel_scope_name=\"supervisor\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "stats_channel_mrk_change_len{otel_scope_name=\"supervisor\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Controls changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "stats_channel_ctrl_change_cap{otel_scope_name=\"supervisor\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "stats_channel_ctrl_change_len{otel_scope_name=\"supervisor\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Processor commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "stats_channel_processor_comm_cap{otel_scope_name=\"supervisor\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "stats_channel_processor_comm_len{otel_scope_name=\"supervisor\", radiantlogic_io_environment=\"$environment\"}",
     "legendFormat": "current"
    }
   ]
  }
 ]
}