{
 "title": "IDO - Observations - Timings",
 "tags": [
  "monitoring",
  "identity-observability",
  "supervisor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{app_kubernetes_io_component=\"observation-supervisor\"},radiantlogic_io_environment)"
    }
   },
   {
    "name": "obs_name",
    "label": "Observation",
    "query": {
     "query": "label_values(observation_timing_norm_milliseconds_count{radiantlogic_io_environment=\"$environment\"},observation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(observation_timing_nb_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Cumulated duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (observation_timing_norm_milliseconds_sum{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Observation $obs_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "obs_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of executions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "observation_timing_nb_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\", observation=\"$obs_name\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Cumulated duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "observation_timing_norm_milliseconds_sum{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\", observation=\"$obs_name\"}",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Differential",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "observation_timing_norm_milliseconds_bucket{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\", observation=\"$obs_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Differential by time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "observation_timing_norm_milliseconds_bucket{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\", observation=\"$obs_name\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Created",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "observation_timing_created_milliseconds_bucket{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\", observation=\"$obs_name\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Updated",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "observation_timing_updated_milliseconds_bucket{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\", observation=\"$obs_name\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Full",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "observation_timing_full_milliseconds_bucket{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\", observation=\"$obs_name\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}