{
 "title": "IDO - Observations - Functional",
 "tags": [
  "monitoring",
  "identity-observability",
  "supervisor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{app_kubernetes_io_component=\"observation-supervisor\"}, radiantlogic_io_environment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Observations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processor_observations_count{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Observations"
    }
   ]
  },
  {
   "title": "Enabled observations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processor_observations_count_enabled{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Enabled observations"
    }
   ]
  },
  {
   "title": "Triggers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processor_triggers_count{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Triggers"
    }
   ]
  },
  {
   "title": "Markers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processor_marks_count{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Markers"
    }
   ]
  },
  {
   "title": "Controls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processor_controls_count{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Controls"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(container) (processor_errors_count_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Observation edges changes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processor_observed_change_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Total:"
    },
    {
     "expr": "processor_observed_change_add_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Added:"
    },
    {
     "expr": "processor_observed_change_delete_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
     "legendFormat": "Deleted:"
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "processor_events_received_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Received"
      },
      {
       "expr": "processor_events_processed_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Processed"
      },
      {
       "expr": "processor_events_invalid_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Invalid"
      }
     ]
    },
    {
     "title": "Stream events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "stream_events_received_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Received"
      },
      {
       "expr": "stream_events_commited_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "stream_events_error_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "Topic events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "topic_events_received_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Received"
      },
      {
       "expr": "topic_events_commited_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "topic_events_error_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "Risk messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "risks_messages_main_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Main messages"
      },
      {
       "expr": "risks_messages_save_total{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Save messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "stream_processing_nb{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Nb messages"
      }
     ]
    },
    {
     "title": "Risk messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "stream_risks_nb{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Nb messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Observation states",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Completed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "observations_state_completed{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Disabled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "targets": [
      {
       "expr": "observations_state_disabled{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "targets": [
      {
       "expr": "observations_state_error{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Computing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "observations_state_computing{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Postponed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "targets": [
      {
       "expr": "observations_state_postponed{radiantlogic_io_environment=\"$environment\", app_kubernetes_io_component=\"observation-supervisor\"}",
       "legendFormat": "Completed"
      }
     ]
    }
   ]
  }
 ]
}