{
 "title": "IDO - System",
 "tags": [
  "system",
  "identity-observability",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({radiantlogic_io_app=\"identity-observability\"},radiantlogic_io_environment)"
    }
   },
   { "name": "Filters" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({radiantlogic_io_environment=\"$environment\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource usage per container",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{name!=\"\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_working_set_bytes{image!=\"\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Top 5 CPU Intense Pods (mcores)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]) * 1000) by (pod))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Total pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container_name!=\"POD\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage (mcores)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=\"$namespace\"}[5m]) * 1000) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}