{
 "title": "IDO - Writeback service",
 "tags": [
  "writeback-service",
  "monitoring",
  "identity-observability"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(up{app_kubernetes_io_component=\"writeback\"}, radiantlogic_io_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "95th percentile request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wbs_request_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Update Request Failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wbs_request_failures_total{radiantlogic_io_environment=\"$environment\", endpoint=\"/update\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Failed Requests by Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (status) (wbs_request_failures_total{radiantlogic_io_environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writeback Failures on Update",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count by(status) (wbs_writeback_failures_total{radiantlogic_io_environment=\"$environment\", action=\"update\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writeback Failures on Delete",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count by(status) (wbs_writeback_failures_total{radiantlogic_io_environment=\"$environment\", action=\"delete\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writeback Failures on Add",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count by(status) (wbs_writeback_failures_total{radiantlogic_io_environment=\"$environment\", action=\"add\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IDDM Writes Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wbs_write2iddm_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph DB Writes Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wbs_write2graph_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IDDM Writes Bucketed latency density",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(wbs_write2iddm_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph DB Writes Bucketed latency density",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(wbs_write2graph_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IDDM Writes Current latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wbs_write2iddm_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph DB Writes Current latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wbs_write2graph_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IDDM Writes Average latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(wbs_write2iddm_latency_seconds_sum{radiantlogic_io_environment=\"$environment\"}[1m])) / avg(rate(wbs_write2iddm_latency_seconds_count{radiantlogic_io_environment=\"$environment\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph DB Writes Average latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(wbs_write2graph_latency_seconds_sum{radiantlogic_io_environment=\"$environment\"}[1m])) / avg(rate(wbs_write2graph_latency_seconds_count{radiantlogic_io_environment=\"$environment\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IDDM Writes latency by action",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, action) (rate(wbs_write2iddm_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph DB Writes latency by action",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, action) (rate(wbs_write2graph_latency_seconds_bucket{radiantlogic_io_environment=\"$environment\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}