apiVersion: v1
kind: Secret
metadata:
  name: creds-{{ template "cfs.fullname" . }}
  labels:
    app: {{ template "cfs.fullname" . }}
    chart: "{{ template "cfs.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.fid.userName }} 
  username:  {{ .Values.fid.userName | b64enc | quote }}
  {{- end }}
  {{- if .Values.fid.password }}
  password:  {{ .Values.fid.password | b64enc | quote }} # if present uses the given value and base64 encodes it
  {{- else }}
  password: {{ randAlphaNum 12 | b64enc | quote }} # if not present creates a random alphanumeric password fo 12 char length
  {{- end }}
  {{- if .Values.cfs.machineKey }}
  machine-key:  {{ .Values.cfs.machineKey | quote }} 
  {{- end }}
