apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfs.fullname" . }}-master
  labels:
    {{- include "cfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      protocol: TCP
      name: https
  selector:
    {{- include "cfs.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfs.fullname" . }}-smtp
  labels:
    {{- include "cfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 25
      protocol: TCP
      name: smtp
  selector:
    {{- include "cfs.selectorLabels" . | nindent 4 }}
  type: ClusterIP
