{{- if eq .Values.postgresql.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres_init_script
data:
  agents_init_script.sql: |
    CREATE DATABASE agentsdb;
    CREATE USER agentsadmin WITH ENCRYPTED PASSWORD '9iKnkK4Xzi';
    GRANT ALL PRIVILEGES ON DATABASE agentsdb TO agentsadmin;
  eoc_init_script.sql: |
    CREATE DATABASE eocdb;
    CREATE USER eocadmin WITH ENCRYPTED PASSWORD '9iKnkK4Xzi';
    GRANT ALL PRIVILEGES ON DATABASE eocdb TO eocadmin;
{{- end }}
