{{- if eq .Values.curator.enabled true }}
{{- if .Values.curator.rbac.enabled  }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: curator-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "patch"]
{{- if .Values.curator.psp.create }}
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - curator-psp
{{- end -}}
{{- end -}}
{{- end }}
