{{- if eq .Values.curator.enabled true }}
{{- if and .Values.curator.serviceAccount.create .Values.curator.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curator-sa
  {{- if .Values.curator.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.curator.serviceAccount.annotations | nindent 4 }}
  {{- end }}

{{- end }}
{{- end }}
