name: Lint and Test FID Charts with Nightly Image

on:
  workflow_dispatch:
  schedule:
    - cron: "* 0 * * *"
  pull_request:
    paths:
      - 'charts/fid/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          helm repo add radiantone https://radiantlogic-devops.github.io/helm
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add elastic https://helm.elastic.co
          helm repo add kibana https://helm.elastic.co

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          config: .config/kind.yaml

      - name: Kind cluster-info
        run: |
          kubectl cluster-info --context kind-chart-testing
          kubectl get nodes --context kind-chart-testing

      - name: Run chart-testing (install)
        run: |
          ct install --charts=charts/fid --helm-extra-args="--timeout=15m0s" --helm-extra-set-args="--set=fid.license=${{ secrets.RADIANTONE_LICENSE }} --set=dependencies.zookeeper.enabled=true --set=replicaCount=2 \
                             --set=image.repository=radiantone/fid-nightly --set=image.tag=latest \
                             --set=imageCredentials.enabled=true --set=imageCredentials.username=${{ secrets.DOCKER_USERNAME }} --set=imageCredentials.password=${{ secrets.DOCKER_PASSWORD }} \
                             --set=imageCredentials.email=${{ secrets.DOCKER_EMAIL }} --set=imagePullSecrets[0].name=regcred" --debug
